# Introduction {-}

Does civic engagement through public pressure campaigns affect agency rulemaking? I examine who participates in public pressure campaigns and why, whether they affect congressional oversight, and whether they affect policy. Answering these questions informs our understanding of bureaucratic politics and interest group lobbying, organizing, and mobilizing tactics. At a time when the vast majority of federal policy is made in the bureaucracy, the relationship between citizens and government depends on bureaucratic policymaking.  If ordinary people have a voice in bureaucratic policymaking, I argue, it is through public pressure campaigns. The capacities required to influence national-level policy are those of organized groups, not individuals acting alone. Thus, understanding the nature and effects of these campaigns is key to understanding modern democracy. 

With the rise of the administrative state, U.S. federal agencies have
become a major site of policymaking and political conflict. By some
estimates, upward of 90% of legally binding U.S. federal policy is now
written by agencies. Agency rules are revised much more frequently than
statutory law [@Wagner2017]. In the years or decades between
legislative enactments, federal agencies make legally-binding rules
interpreting and reinterpreting old statutes to address emerging issues
and priorities. Examples are striking: Many effects of the Dodd-Frank Wall
Street Reform and Consumer Protection Act were largely unknown until the
specific regulations were written, and it continues to change as these
rules are revised. Congress authorizes billions in grants, subsidies, and
leases for public lands, but who gets them depends on agency policy. In
the decades since the last major environmental legislation, agencies
have written thousands of pages of new environmental regulations and
thousands more changing tack under each new administration. These
revisions significantly shape lives and fortunes. For example, in 2006,
citing the authority of statutes last amended in the 1950s, the Justice
Department's Bureau of Prisons proposed a rule restricting eligibility
for parole. In 2016, the Bureau withdrew this rule and announced it
would require fewer contracts with prison companies,
precipitating a 50% loss of industry stock value. Six months later, a
new administration announced these policies would again be reversed,
leading to a 130% increase in industry stock value. Agency rulemaking
matters.

Less clear, however, is how the new centrality of agency rulemaking fits
with democracy. In addition to the bureaucracy's complex relationships with
the president and Congress, agencies have complex and poorly understood
relationships with the public and advocacy groups. Relationships with
constituent groups may even provide agencies with a degree of "autonomy" from their official principals [@Carpenter2001].

<!-- DEMOCRACY has problems and bureaucratic solutions-->
Large democracies face two big problems. First, they are vulnerable to fleeting passions and demagogues. To combat this, many decisions are left to experts who, ideally, exercise judgment loosely guided by the public. Second, everyone cannot vote on every decision. We thus delegate power to representatives (who then delegate it to deputies), create temporary mini-publics, or solicit input from those most affected or moved by a public decision.^[As imagined by @Dahl1989, mini-publics are representative, selected at random, and deliberative. Besides juries, however, randomly selected deliberative bodies are rare. Instead, citizens more often engage in government decisions when given opportunities to opt-in, such as hearings, petitions, and public comment periods. These mechanisms of engagement generate a different, more contentious flavor of public input than the discourse imagined by scholars who focus on deliberation.] Most policy is then made by bureaucrats, supposedly guided indirectly through elected representatives and directly by limited public input. Of the thousands of policies that the institutions of government make each year, direct public input tends to be limited to only the very most contentious policy debates.

Both of these problems converge in the bureaucracy. Bureaucracies are run by experts who are deputized by elected officials (or by their deputy's deputy's deputy). Many bureaucracies also have procedures that create opportunities for public input, and it is far from clear how bureaucratic decisions are to balance expertise, accountability to elected officials, and responsiveness to public input in policymaking. 
 

<!--
TODO THE BELOW IS REPEATED FROM WHYMAIL--SORT OUT BOOK FROM WHYMAIL MATERIAL! 
-->

Participatory processes like public comment periods, where government
agencies must solicit public input on draft policies, are said to
provide political oversight opportunities [@Balla1998; @McCubbins1984],
democratic legitimacy [@Croley2003; @Rosenbloom2003], and new technical
information [@Yackee2006JPART; @Nelson2012]. While recent scholarship on
agency policymaking has shed light on the sophisticated lobbying by
businesses and political insiders, we know surprisingly little about the vast majority of public comments which are submitted by ordinary people
as part of public pressure campaigns.

In 2018, the Administrative Conference of the United States (ACUS)
    identified mass commenting as a top issue in administrative law. In
    their report to ACUS, @SantAmbrogio2018 conclude, "The 'mass
    comments' occasionally submitted in great volume in highly salient
    rulemakings are one of the more vexing challenges facing agencies in
    recent years. Mass comments are typically the result of orchestrated
    campaigns by advocacy groups to persuade members or other
    like-minded individuals to express support for or opposition to an
    agency's proposed rule." Mass comment campaigns are known to drive
    significant participation of ordinary people in Environmental
    Protection Agency rulemaking
    [@Judge-Lord2019; @Potter2017; @Balla2018]. @Cuellar2005, who
    examines public input on three rules, finds that ordinary people
    made up the majority of commenters demonstrating "demand among the
    mass public for a seat at the table in the regulatory process." 

    
Activists frequently target
agency policymaking with letter-writing campaigns, petitions, protests,
and mobilizing people to attend hearings, all classic examples of "civic
engagement" [@Verba1987]. As I show in \@ref{why-results}, most comments submitted to
    regulations.gov are form comments, more akin to petition signatures than sophisticated lobbying. Indeed, approximately 40 million out of
    50 million (80%) of these public comments mobilized by just 100
    advocacy organizations.
    Yet civic engagement remains poorly understood
in the context of bureaucratic policymaking.

These occasional bursts of civic engagement in bureaucratic policymaking
raise practical and theoretical questions for the practice of
democracy. 
These questions, in turn, hinge on unanswered empirical
questions: Do these campaigns affect policy? If so, by what mechanisms?
Existing research finds that commenters believe their comments matter
[@Yackee2015JPART] and that the number of public comments varies across
agencies and policy processes
[@Judge-Lord2019; @Libgober2018; @Moore2017], but the relationship
between the scale of public engagement and policy change remains
untested. Indeed, we have much to understand about the causes
and effects of these campaigns before we are in a position to ask if
they are a mechanism for groups to influence policy. Most critically, we
must understand who mobilizes public pressure campaigns and why.

## Motivation {-}

Leading models of influence in bureaucratic policymaking focus on two key political forces: sophisticated interest group lobbying and political oversight. 
As bureaucrats learn about policy problems and balance interest-group demands, public comment processes allow lobbying organizations to provide useful technical information and inform decision-makers of their preferences on draft policies. 
Agencies may then update policy positions within constraints imposed by their political principals.

While this may describe most cases of bureaucratic policymaking, these models neither explain nor account for the contentious politics that occasionally inspire millions of ordinary people to respond to calls for public input on draft agency policies. Thus, political scientists have largely ignored mass engagement in bureaucratic policymaking, leaving a weak empirical base for normative and prescriptive work. 
Like other forms of mass political participation, such as protests and letter-writing campaigns, 
mass public comments on draft agency rules provide no new technical information. <!--%In this sense, they are not useful. -->
Nor do they wield any formal authority to reward or sanction bureaucrats, as comments from a Members of Congress might. 
The number on each side, be it ten or ten million, has no legal import for an agency's response. 

<!--
% Policymakers may very well pay no attention to them. 
%Instead, scholars focus on the sophisticated lobbying efforts of powerful interest groups, whose role in shaping policy has been theoretically developed and empirically tested.
% If our models and conventional wisdom is correct, why do
Yet, agencies occasionally receive input from a large number of ordinary people. %Why? 
--> 

How, if at all, should scholars incorporate mass engagement into models of bureaucratic policymaking? 

I take up a part of this question in each of the following chapters. Each draws on different but overlapping literatures to better understand bureaucratic policymaking. Chapter \@ref(macro) brings in the literature on public opinion and the attention of parties to different issues over time, zooming out to the broadest relationships between mass politics and policy outputs. Chapter \@ref(whymail) brings the focus to specific policy fights, bringing in literature interest-group mobilization to understand why public pressure campaigns target agencies in the first place. Chapter \@ref(influence) focuses squarely on the classic bureaucratic politics question of interest group influence in policymaking but expanded to account for public pressure campaigns. Chapter \ref(EJ) then zooms out again, this time bringing in the literature on social movement pressure. As these chapters address the literature on public opinion, party politics, interest groups, lobbying, and social movements in turn, my review of this literature in this introduction is brief. My aim is to provide a general foundation.

<!--> TODO: intro to pol-sci lit that is too broad for elsewhere? -->

## Rulemaking {-}

The theories about the drivers of public participation and the mechanisms by which it may affect policy that I advance and test in the following chapters may apply to many contexts where public pressure is aimed at decision-makers. My empirical terrain, however, is policymaking by U.S. federal agencies, specifically a policymaking process called Notice-and-comment rulemaking prescribed in the Administrative Procedures Act. The APA governs the process by which federal agencies develop and issue legally binding policies. It requires agencies to publish proposed (draft) and final policies (rules) in the Federal Register and provide opportunities for the public to comment on draft rules.

<!-- > TODO: General into to scholarship on rulemaking, @Yackee2019, @Potter2016, @PotterShipan2019 -->


<!--TODO SUSAN: "instead of presidents, congress, and judicial review, add a general section (with, say, 2-4 meaty paragraphs with lots of citations to key works on bureaucratic politics).   This section should explain about what we know about the public bureaucracy’s generally – they are hierarchical, technocratic, driven by expertise, have odd political accountability relationships, are not elected, etc and then introduce rulemaking as one of the most important policy tools of bureaucracies.  Here you should comment on judicial review, and how it “matters” to rulemaking.  Your reader needs to know this contextual information to understand how and why mass comments might matter to bureaucratic officials in later chapters." -->

<!-- ### Presidential Agendas and Oversight -->

<!-- > TODO: General overview of the president's role in rulemaking, @Ferejohn1990, @Potter2019 -->

<!-- ### Congressional Agendas and Oversight -->

<!-- > TODO: General overview of Congress's role in rulemaking, @McCubbins1984, @McCubbins1987, @Huber2002, @Macdonald, @Feinstein2017, @Lowande2018JOP, @Lowande2017, @Clinton2014AJPS -->

<!-- #### Judicial Review -->

<!-- > TODO: General overview of judicial review, @judgelord2016MPSA, @Ferejohn1990, -->

