# Summary {-}

With 90% of U.S. law now made in the executive branch, agency rulemaking is now a major site of political conflict. My dissertation examines the effects of public pressure campaigns in rulemaking, a technocratic policy process where "public participation" is usually limited to sophisticated lobbying but occasionally includes millions of people mobilized by public pressure campaigns. Public comment periods on proposed policies purport to provide democratic accountability. Yet theories of bureaucratic policymaking largely ignore the occasional bursts of civic engagement that generate the vast majority of public comments on proposed rules. To fill this gap, I build and test theories about the role of public pressure in policymaking. I collect and analyze millions of public comments to develop the first systematic measures of civic engagement and influence in bureaucratic policymaking. Chapters address (1) how and why groups mobilize ordinary people to engage in rulemaking; (2) how public pressure draws the attention of elected officials; (3) how public pressure affects policy; and (4) how environmental justice campaigns have used  participation in rulemaking to affect policy.

The first chapter addresses who participates in public pressure campaigns and why. Are public pressure campaigns, like other lobbying tactics, primarily used by well-resourced groups to create an impression of public support? Or are they better understood as conflict expansion tactics used by less-resourced groups? Using text analysis methods underlying plagiarism detection, I match millions of individual public comments to pressure-group campaigns. Contrary to research on other forms of lobbying, I find that mass comment campaigns are almost always a conflict expansion tactic, rather than well-resourced groups creating an impression of public support. Contrary to research on other forms of political participation, I find no evidence of negativity bias in public comments. Indeed, from 2005 to 2017, most comments supported proposed rules.

Second, I examine the effect of public pressure campaigns on congressional oversight. I assess whether legislators are more likely to engage in rulemaking when advocacy groups mobilize public pressure. To do so, I collect and code thousands of comments from Members of Congress on proposed rules with and without public pressure campaigns. These data also allow me to assess congressional oversight as a mediator in policy influence, i.e., the extent to which public pressure campaigns affect agency decisionmakers directly or indirectly through their effects on elected officials' oversight behaviors.

Third, I use a mix of hand-coding and computational text analysis methods to assess whether public pressure campaigns increase lobbying success. I develop computational methods to identify lobbying coalitions and estimate lobbying success. I validate these methods against random samples of rules with a mass-comment campaign and without a mass-comment campaign that I hand-code for whether each coalition got the policy outcome they sought. I then assess potential mechanisms by which mass public engagement may affect policy by revealing different types of information to decisionmakers. 
<!--Of primary interest is the extent to which public pressure campaigns affect agency decisionmakers directly or indirectly through their effects on elected officials' oversight behaviors. I test this by assessing congressional oversight as a causal mediator using a subset of rules where I collect and code correspondence from Member of Congress to agencies about proposed agency rules.-->
Finally, I ground my broader analysis by focusing on the impact of environmental justice campaigns in rulemaking. I examine the discursive effects of environmental justice claims both qualitatively and quantitatively. I write about the role of Native activists and environmental groups in shaping federal environmental regulations. Looking across over 20,000 draft regulations that failed to address environmental justice issues, I find that agencies are more likely to add language addressing environmental justice in their final rules when public comments raise environmental justice concerns. However, I have yet to find evidence that mass comment campaigns make this more likely.