## Reforming rulemaking

Each week, students in my public policy class must write to an elected official or comment on a proposed agency rule and then post about it in the class forum. 

But college students should not be the target demographic for notice and comment rulemaking--they are too informed and have too much time to write thoughtful comments. If we wish to realize the ideals of the APA, we must broaden participation. Can we do this? Is it worthwhile? Many scholars assume not, but the data offer some hope. 

###  The debate in administrative law {-}

#### Participatory democracy optimists {-}

Optomists see notice and comment is the "purest example of participatory democracy in actual American governance." The process is technically open to anyone with an opinion to offer and agencies are, to an extent, required to resond to substantive ideas. 

#### "Regulatory democracy" reformers {-}

@Cuellar2014 <!--and @Jonson2013-->
argues that rulemaking could be more discursive. @Mendelson2011 found that agencies often discard non-technical comments, but argues that they shouldn't becuase mass comments contain valuable information. For this camp, the quality of the public debate is more important than the total number of people, their affiliations, or their biases. They emphasize the transformative power of discourse. 
<!--
"To reach an understanding in a dialogue is not merely a matter of putting oneself forward and successfully asserting one's own point of view, but being transformed into a communion in which we do not remain what we were." (Gadamer)
-->

#### Pluralist reformers {-}

A different brand of reformer focuses less on discource and more on interest group representation. Pluralist reformers argue that lobbying groups should have to disclose there membership, funding, and decisionmaking processes (Seifter 2016). In this view, organized groups, not individuals, are the central actors in public comment processes. However, becuase agencies often lack information about groups, it is difficult to know how well they represent the people they claim to. Interest groups faithful representation of their memebers is crucial to pluralist ideas of democracy.  


#### Rational pluralists {-}

Another group of scholars sees organized interst groups and experts that can provied credible information. In this view, random or self-selecting members of the general public are not apropriate participants. "The goal of e-rulemaking is to more fully capture such credible, specific, and relevant information, not to solicit the views of random, self-nominating members of the public" (Herz 2016). Speaking on the topic of mass coment campaigns, Oliver Sherouse, a regulatory economist at the Small Business Administration, expressed the same sentiment: 

> "It's worth remembering why we have a public comment process in the first place, which is that the public has knowledge that regulators do not have and that they need to do their jobs well...how do the poor quality mass comments affect small buisnesses in the comment process? The most obvious problem would be if legitmate small buisness concerns are just lost in the flood." (GSA 2019a, p. 31-32)

Sherhouse raised an additional concern that mass-comment campaigns might distract people from writing their own, more informative comment. While recognising that "not everyone who does not sign onto that kind of [mass] comment would be willing to write a high quality one," the tradeoff of a few "quality" comments for many "poor quality" comments is worthwhile. (GSA 2019a, p. 32)

However, Sherouse was also wary about dismissing mass comments. 
> "A good point is not less of a good point because 10,000 people happen to agree with it." (GSA 2019a, p. 32)



#### Skeptics {-}

The most skeptical camp goes even further, arguing that open solicitations to the general public should be aboloshed. 

### Challenges {-}

#### Fraud  {-}

(The Wall Street Journal](https://www.wsj.com/articles/many-comments-critical-of-fiduciary-rule-are-fake-1514370601) reported that 40% of comments on one Department of Labor rule used fradulent identities. 

<!--
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">At the State of the Net conference, <a href="https://twitter.com/JRosenworcel?ref_src=twsrc%5Etfw">@JRosenworcel</a> says people from across the USA, across politics persuasions, have found their names &amp; identities stolen &amp; used in the <a href="https://twitter.com/FCC?ref_src=twsrc%5Etfw">@FCC</a> net neutrality rule making. 2 million total. ~500K from Russian email addresses. <a href="https://twitter.com/hashtag/sotn2018?src=hash&amp;ref_src=twsrc%5Etfw">#sotn2018</a> <a href="https://t.co/zCUNlssA54">pic.twitter.com/zCUNlssA54</a></p>&mdash; Alex Howard (@digiphile) <a href="https://twitter.com/digiphile/status/958084755605553152?ref_src=twsrc%5Etfw">January 29, 2018</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
-->



### Reforms {-}

Can the unwashed masses provide useful information to agencies? My answer is yes. Will this information be biased? Yes, but all information provided by lobbying groups has a bias, the task is to make biases transparent, and reforms could do this. 

1. First we must dispense with the idea that agencies merely implement the law. The APA provides for public participation because ideal of direct democracy might affect the important substantive policy made by agencies. Indeed, agencies are often seeking comment on revisions to rules based on authority delegated decades ago. Agency must make policy to satisfy their mandates. The present question is one of process. Calling for greater congressional oversight or presidential control side-steps the issue--by what process should agencies make policy?  (Indeed, @Potter2019 shows us that agencies often side-step oversight, making their procedural rules all the more important.)



2. Critics may argue that opening the door wider to petition campaigns lets in biases. Indeed we know that people who opt to participate are disproportionately privleged. In an unequal socieity, we have unequal participation, but higher barriers to entry only make this worse.  More problematic is the idea that well-funded group who typically dominate rule making (Yackee) will sponsor astro-turf campaigns, thus creating a false impression of public support. This is a real concern. If dark money can secretly drive impressions of support for a policy, the case for expanding participation is weekend.  Hopefully, my analysis suggests that this is uncommon. the fast 
The fact that we do not observe it now does not mean it will not occur, but agencies could b

Reforms along the lines have been suggested. ___ would like polls. Nationally representative polling may be a good investment for some rules, but we know from polling research that individuals do not always have clearly formed opinions and much depends on question wording. The reality is that american politics is animated through groups--people rely on organizations they trust to keep them informed and engaged. In classic pluralist fashion, organizations claim to represent segments of the population in rulemaking. Because these organizations 

Raso suggests similar reforms 

as others have pointed out 

As the moderator of my class's forum I can co-sign research on discursive democracy initiatives that realizing transformative discourse is difficult. the ideal of "transformed into something" is laudable but people are busy and any barrier to participation will massively reduce participation. Participation already follows a log scale distribution, with most rules receiving no comments--even major rules, on average receive less than 10. 

#### Aims of reform {-}

**Lower barriers to participation.**

The main barier to participation in rulemaking is information. Even people with relativly high social capital like small business owners rarely participate because they do not know about the opportunity or lack the time necessary to engage. 

> "they might only find out about a proposed regulation when they're presented with one of these mass comments.  And they might not have time to go back and investigate and then write a full comment letter right before the comment period is going to close.  Because there aren't a lot of small business owners who read the Federal Register every day...writing a detailed comment letter is hard work." - Oliver Sherhouse (GSA 2019a, p. 33)

**Increase transparency.**

**Reduce the cost of extracting information from comments.** Reformers often highlight the value of linking comments to particular questions or sections of a draft rule. Technology can certianly improve sophisticated debates about a rule's technical provisions. Indeed, sophisticated commentors have adopted track-changes technoligy to provide marked up versions of draft rules.

New technologies may provide an even more important role in gleaning political information from the "torrents of email" and "vexing challenge" posed by mass comment campaigns. 

**Gaurd against fraud.**

#### Parsing the questions {-}

Agencies often specific ask questions and solicit comment on specific topics in an NPRM. These topics offer an intitial structure to allow commenters to self identify the topics of their comments. The American Bar Association's Section of Administrative Law and Regulatory Practice reccomends "technology that would allow agencies to identify categories that commenters could select when submitting comments." To stay open to new ideas, lobbying groups should be allowed to petition the agency to add topics to the menue or ask additional questions. 

For example, agencies may encourage groups to mobilize in support of the groups' answer to the questions that agencies ask. Given past trends, this will likely take the form of petition campaigns and agencies should have a mechanism to receive those comments as such. 

#### Offering answers {-}

Agencies could also lower the bar to participation by posting answers to their questions from different organizations and allow people to co-sign them or disagree with them. This is both easier for participants and requires less work for agencies to interpret where the commenter stands. 

2) The risk of astro-turf is real under any public comment system (including the current one), but transparency requirements can go a long way. Organizations or individuals acting in their professional capacity as organizations (not individuals) should be required to disclose where the money the paid for them to produce their comments came from. Likewise, organizations running campaigns should disclose the sources of funding for the campaigns and how how much they spent mobilizing public support. These numbers will provide a helpful demomoninator for agencies to gaduge public enthusiasm.

---



#### ACUS Report {-}



---

#### Increasing transparency and public participation (GSA-2019-02) {-}

On January 30th, 2020, the Government Services Administration held a hearing on the topic of mass comments. The three invited speakers represented the National Association of Manufacturers, the Small Business Administration, and MITRE. A federerally funded technology research and development. These three guests embody important aspects of how public comment is seen. First, public comment is most often utilized by business groups like NAM ("power users of the regulatory process" as Hedern put it) and thus represent the users for whom public comment technology is designed. NAM does not sponsor mass comment campaigns. Perhaps they have a stake in delegitimizing mass comment campaigns that occasionally mobilized on the opposing side, but the reason they are on this panel is simply that they are the archotypical user. Second, agencies like the Small Business Administration are the ones who must deal with the "challenge" of mass comment campaings. Third, technology consultants represent the way in which mass comment campaings are primarily viewed as a technological challenge.

Another important feature of this policy area is it's tight-knit epistimic community. As observed by Mr. Hedren:

> "it's a little alrming to me in some respects to see that, looking out into the crowd, I think I know about half of you on a first-name basis. So, we probably neeed a little bit more fresh blood in this regulatory nerd community." - Patrick Hedren, National Association of Manufactures

<!-- > And we've very much kind of what, I would consider power users of the regulatory process. We have a clear point of view for the
  manufacturing sector.  We weigh in frequently in agency actions across the entire federal family, whether they're independent agencies or executive agencies and departments.  So we have quite a lot of experience and exposure to the tools that really underpin the system.  And there's a lot of value in those tools.-->
  

#### Gaurding against fraud {-}

As with any form of public participation, fraud merits attention. If organizations submit comments on behalf of people who do not exist or did not consent, this is akin to fraudulent petition signatures or fake constituent letters being sent to Members of Congress. 

**Authentication.** Matt Cutts (acting director of the U.S. Digital Service) suggest CAPTCHAS, email confirmations, and multi-factor authentication. If comments are allowed to be collected by third parties like the Sierra Club, the government can encourage but *may not be able to enforce the use of CAPTCHAS*. Requireing confirmation or authentication by email or phone alone would be a barrier to participation. Requiring both could be prohibiative. 

The most secure approach that allows third-parties to gather comments may be to authenticate each comment by asking each commentor to provide an email address or phone number at which to recieve a message asking them to confirm the text of their comment. 

Asking for a second interaction with the agency raises the cost of participation but may also make participation a slightly richer expierence (as Dan Walters suggested on twitter). People may be more likely to feel that their voice was heard. Of course, many people will fail to confirm their authenticate their comment, but like mass comments themselves, the number of people willing to take the time to authenticate offers information on the intensity of genuine support. Unauthenticated comments need not be discounted, but authenticated comments may indicate stronger prefrences. 

More importantly, authentication gaurds against idneity theft. It is difficult to provide a large number of fake phone numbers and real phone numbers used fraudently would likely generate complaints, alerting the agency that the campaign may be engaging in fraud. Again, fraud complaints need not discount an entire campaign. Opponents of a campaign by the Sierra Club, for example, could submit fraudlient comments through their system in order to complain when asked to authenticate and thus cast doubt over the campaign. However, a legitimate campaign will also have a portion that will authenticate, allowing rough estimates of the scale of true support versus fraud. 

Some means of authentication, such as email, may be slightly more open to fraud than others, like texts, but the benifits to lower barriers to participation may outweigh the greater risk of fraud. 

Because mass comment campaigns include a fairly large number of individuals, especially if the barriers to participation are lower, there are many opportunities to identify fraud of any significant scale, and the stakes of a few fraudulent comments slipping through the cracks are low. 

**Should agencies accecpt anonomus comments?**

There are good reasons to accept technical information from anonomus sources. For example, they may fear retaliation. However, anonmus comments should not be used to infer political information. This distinction supports two tracks with distinct requirments. An agency may want to allow sophisticated anonomus comments to be co-signed by large numbers of authenticated supporters, thus alowing insiders with necessary knowlege to make sopisticated arguments, but also much to lose to put ideas into pulic nad the agency to gadge public reacation to those ideas. 

<!---

# April


FDA 
- used to use interns 
- put comments into an excel
"by hand and I"--"Included the prevelent postcard campaings"
- "as the number grouws, so do the tools"
- "don't see this slowing down anytime soon"
using text anslysis to identify topic and theme
- uses contractors 

FDA CONTRACTOR FROM SAS

- main themes/concerns 
- - themes that require a common response
- - new issue or similar to previous comment
- who are the commenters 
- id fake and mass comments
- text clustering (unsupervised)
- unclear if using plararism (seems not, just did it by hand for one comment in the cluster)
- entitiy extraction
-

# Questions 
- What portion of FDA rules use contractors to process comments? What portion of comments do contractors process?

# Software 

#### Rule revision {-}

Open source 

gsa github 

#### Comment analysis  {-}

open code 
open source 

Will the code text analysis used be part of the record or otherwise made public? Will it use open-source software?

#### API



<!---



### Existing studies

#### Studies cited by GSA

1. Commentsonthebackgroundinformationprovidedabouttheprogram 
2. Commentsonthevalidityofthestudiesthemselves
3. Comments on other research that the program staff should be aware of


Cary Coglianese, S. S. (2004, November). RECOMMENDATIONS FOR THE DESIGN OF THE FEDERAL DOCKET MANAGEMENT SYSTEM. Retrieved March 2nd, 2020, from GWIPP WORKING PAPER SERIES: https://gwipp.gwu.edu/sites/g/files/zaxdzs2181/f/downloads/Working_Paper_008 _FedDocket.pdf
Farina, C. R. (2008). Achieving the Potential: The Future of Federal eRulemaking: A Report to Congress and the President. Retrieved March 3rd, 2020, from Scholarship @Cornell Law: A Digital Repository: https://scholarship.law.cornell.edu/cgi/viewcontent.cgi?article=2505&context=fac pub
Rubin, T. (2018, December 1st). REGULATIONS.GOV AND THE FEDERAL DOCKET MANAGEMENT SYSTEM. Retrieved March 3rd, 2020, from Administrative Conference of the United States: https://www.acus.gov/sites/default/files/documents/Regulations.gov%20Report% 20FINAL%2012%203%202018.pdf
The Federal Rulemaking Process: An Overview. (2013, June 17th). Retrieved March 3rd, 2020, from EveryCRSreport.com: https://www.everycrsreport.com/reports/RL32240.html

--->