# Reforming the Policy Process {#policy}

Each week, students in my public policy class must write to an elected official or comment on a proposed agency rule and then post about it in the class forum. 
But college students should not be the target demographic for notice and comment rulemaking---they are too informed and have too much time to write thoughtful comments. If we wish to realize the ideals of the Administrative Procedure Act, we must broaden participation. Can we do this? Is it worthwhile? Many scholars assume not, but the data offer some hope. As I shown in Chapter \@ref(whymail), more participation generaly means a more diverse and public-spirited voices at the table. As I show in Chapter \@ref(ej), agencies respond when people raise new concerns, especially when a large number of people raise them. At the same time, there is little evidence that mobilizing more people has an impact on the outcome of particular policy fights. It is possble that narrow private interests are able to strenthen their case by showing evidence of broader public support. However the correlation between pressure campaings backing business interests and lobbying success could also simply be the result of public interest groups also mobilize on policy fights they are likely to loose. 

This chapter reviews dominant ways of thinking about public comments and proposed reforms to participatory processes in light of the empirical evidence in the previous chapters. I start with a sketch of the various positions staked out by administrative law scholars, each rooted in different theories of democracy. I then review several specific challenges and proposed reforms to the policy process. <!--Finally, I extend -->

## Re-thinking Public Participation in Bureaucratic Policymaking

Understanding mass commenting as a form of petitioning, as presented in chapters \@ref(whymail), \@ref(influence), and \@ref(ej), runs against how it is often discussed by scholars and agencies. With a few notable exceptions (e.g., @Cuellar2005; @Mendelson2011; @Rauch2016), administrative law scholars imply that mass commenting is misguided and potentially harmful spam of the technocratic process. 

> "Many fear a surging wave of electronic mass submissions will overwhelm and thus delay agencies with limited resources. Furthermore, some warn us that electronic rulemaking may already have instantiated a sense that rulemaking decisions are akin to a plebiscite." - Stuart W. Shulman (EPA-HQ-OEI-2004-0002-0015)

In a 2020 meeting, Reeve T. Bull, Research Director, Administrative Conference of the United States, summed up the dominant attitude of legal professionals:

> "What are the fundamental goals that the agency and the APA are trying to accomplish by creating this mechanism for public participation?...[W]hen somebody files a comment with an agency, the comments sort of fall into two broad categories...the first type of comment are those expressing fact---providing data to the agency, either supporting the position that it wants to take or opposing the position that it wants to take--and trying to influence the agency's decision making accordingly. 

> The second broad type of [public comments] are those expressing opinions. Now obviously, there's extensive overlap between the two. Pretty much every comment is going to express an opinion one way or the other. But as Steve's data shows, sometimes a comment is nothing but an opinion. It's 'I support this policy' or 'I don't support the policy... the law is very, very clear that with respect to the fact, with respect to data, the agency is legally required to take that into account... With respect to opinion, though, the law is much less clear. Indeed it's not clear whether the agency has to take opinion into account or conversely whether the agency is even permitted to take opinion into account. ...[Agencies] have been very, very consistent in saying the rulemaking process is not a plebiscite. It's not a vote. We're not tabulating the number of comments in favor or against. ...On the part of the public, though, I think the perception is quite a bit different. And I think that people really considered it problematic from their perspective that the agency might take a position that is different from what the vast majority of commenters might have preferred. And with respect to that latter aspect -- the democratic aspect, if you will -- that's where I think a lot of the problems potentially start to arise. 

> I don't think it's ever legitimate in a mass comment campaign for the agency to tabulate the number of comments received and say we got this number of this percentage in favor or against. Even if the comments are 99 percent in one direction or the other, I think that the agency should certainly consider mass comments. They should certainly consider the relevant information -- the facts contained in those comments. But I don't think that the overall number or percentage should ever matter." - Reeve T. Bull, Research Director, Administrative Conference of the United States

In response to public pressure campaigns, agencies often assert that rulemaking is not a plebiscite.

At the same time, agencies frequently do tally up comments on each side. In a 2008 rule regulating border crossing by private aircraft, The U.S. Customs cited the scale of public engagement as providing information on "public sentiment": 
>based on the ample number of comments received by the end of the original comment period, CBP believed that public sentiment was accurately captured.” ([CBP-E8-26621/p-61](https://www.federalregister.gov/d/E8-26621/p-61))

In the preamble to the 2015 Waters of the United States Rule, EPA evoked both majoritarian and pluralist justifications:

>"This final rule reflects the over 1 million public comments on the proposal, the substantial majority of which supported the proposed rule, as well as input provided through the agencies' extensive public outreach effort, which included over 400 meetings nationwide with states, small businesses, farmers, academics, miners, energy companies, counties, municipalities, environmental organizations, other federal agencies, and many others." ([2015-13435/p-67](https://www.federalregister.gov/d/2015-13435/p-67))

EPA Administrator Gina McCarthy testified that EPA "received over one million comments, and 87.1 percent of those comments...are supportive of this rule" [@Lipton2015].
When the EPA issued a new rule under the Trump administration, it noted "a number of comments" in favor of the new definition but "a significant number of comments" in favor of the 2015 definition ([2020-02500/p-231](https://www.federalregister.gov/d/2020-02500/p-231). While not going so far as to explicitly state that a supermajority of commenters opposed the new policy, it is still remarkable that the agency would choose to note quantitative opposition to the policy. 

Agencies also regularly refer to form comments as petitions. When the Bureau of Land Management received 6,948 identical emails that did not cite an organization, they labeled these comments a "Pro Fracking Petition" ([LM-2013-0002-5720](https://www.regulations.gov/comment/BLM-2013-0002-5720)) This text was nearly identical was signed by "Oil and Gas industry individuals" ([BLM-2013-0002-5688](https://www.regulations.gov/comment/BLM-2013-0002-5688)). Another batch of 1,289 nearly identical emails submitted through the social networking website Care2.org was labeled "Anti Fracking Petition" ([BLM-2013-0002-5721](https://www.regulations.gov/comment/BLM-2013-0002-5721))

The organizations running public pressure campaigns are even more explicit that they consider mass comments to be petition signatures, frequently citing mass comments as "Letters in support of [our organization's] Comments" ([NOAA-NMFS-2012-0059-0023](https://www.regulations.gov/comment/NOAA-NMFS-2012-0059-0023)), a "petition from World Wildlife Fund-US (WWF-US), signed by 271,893 WWF-US supporters" ([BOEM-2016-0003-2556](https://www.regulations.gov/comment/BOEM-2016-0003-2556)),
The files containing comments collected by organizations are often named "signatures."

##  The Debate in Administrative Law 

Scholars vary significantly in both the value they place on political information and the extent to which they believe that meaningfully engaging large numbers of people is possible. 

#### Participatory democracy optimists {-}

Optimists see notice and comment as the "purest example of participatory democracy in actual American governance" [@Herz2016]. The process is technically open to anyone with an opinion to offer, and agencies are, to an extent, required to respond to substantive ideas. This optimism is rooted in a volunteerism idea of democracy and a value for inclusive and substantive discourse. It assumes that those who "ought" to be included do not have large barriers beyond the formal rules of the institution. It also assumes that meaningful discourse among those who show up is possible and likely to occur. 

#### "Regulatory democracy" reformers {-}

A related camp is slightly less rosy about the current institutions and practices but is nevertheless optimistic that reforms can at least improve the quality of discourse and thus policy. For these scholars, democracy is more a function of procedure than inclusion. "issues and contributions, information and reasons." 
@Cuellar2014 <!--and @Jonson2013-->
argues that rulemaking could be more discursive. @Mendelson2011 found that agencies often discard non-technical comments but argues that they shouldn't because mass comments contain valuable information. For this camp, the quality of the public debate is more important than the total number of people, their affiliations, or their biases. They emphasize the transformative power of discourse. 
<!--
"To reach an understanding in a dialogue is not merely a matter of putting oneself forward and successfully asserting one's own point of view, but being transformed into a communion in which we do not remain what we were." (Gadamer)

"The democratic procedure for the production of law evidently forms the only post-metaphysical source of legitimacy. But what provides this procedure with its
legitimating force? Discourse theory answers this question with a
simple, and at first glance unlikely, answer: democratic procedure
makes it possible for issues and contributions, information and
reasons to float freely" <!--; it secures a discursive character for political
will-formation; and it thereby grounds the fallibilist assumption
that results issuing from proper procedure are more or less reasonable."
Habermas %>% 

Habermas

intersubjectivity

discourse both presupposes and creates shared expectations 

My impression was that law and discourse both presuppose and create shared expectations: 

"law simultaneously secures symmetrical relationships of reciprocal recognition between abstract bearers of individual rights. These structural similarities between law and communicative action explain why discourses, and thus reflexive forms of communicative action, play a constitutive role for the production (and application) of legal norms."
449 from Between facts and norms









-->

#### Pluralist reformers {-}

A different brand of reformer focuses less on discourse and more on interest group representation. Reform-oriented scholars building on pluralist ideas of representation argue that lobbying groups should be required to disclose their membership, funding, and decision-making processes [@Seifter2016UCLA]. In this view, organized groups, not individuals, are the central actors in public comment processes. However, because agencies often lack information about groups, it is difficult to know how well they represent the people they claim to. Interest groups' faithful representation of their members is crucial to pluralist ideas of democracy. However, reforms requiring groups to disclose information about their funding and membership only go part way to assess groups' representational claims, which often extend well beyond their membership.


#### Rational pluralists {-}

Another group of scholars sees organized interest groups and experts that can provide credible information. In this view, random or self-selecting members of the general public are not appropriate participants. "The goal of e-rulemaking is to more fully capture such credible, specific, and relevant information, not to solicit the views of random, self-nominating members of the public" (Herz 2016). Speaking on the topic of mass comment campaigns, Oliver Sherouse, a regulatory economist at the Small Business Administration, expressed the same sentiment: 

> "It's worth remembering why we have a public comment process in the first place, which is that the public has knowledge that regulators do not have and that they need to do their jobs well...how do the poor quality mass comments affect small businesses in the comment process? The most obvious problem would be if legitimate small business concerns are just lost in the flood." (GSA 2019a, p. 31-32)

Sharehouse raised an additional concern that mass-comment campaigns might distract people from writing their own, more informative comments. While recognizing that "not everyone who does not sign onto that kind of [mass] comment would be willing to write a high-quality one," the tradeoff of a few "quality" comments for many "poor quality" comments is worthwhile. (GSA 2019a, p. 32)

However, Sherouse was also wary about dismissing mass comments. 
> "A good point is not less of a good point because 10,000 people happen to agree with it." (GSA 2019a, p. 32)



#### Skeptics {-}

The most skeptical camp goes even further, arguing that open solicitations to the general public should be abolished. 

<!--
### Challenges 

#### Fraud  {-}

(The Wall Street Journal](https://www.wsj.com/articles/many-comments-critical-of-fiduciary-rule-are-fake-1514370601) reported that 40% of comments on one Department of Labor rule used fraudulent identities. 

<!--
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">At the State of the Net conference, <a href="https://twitter.com/JRosenworcel?ref_src=twsrc%5Etfw">@JRosenworcel</a> says people from across the USA, across politics persuasions, have found their names &amp; identities stolen &amp; used in the <a href="https://twitter.com/FCC?ref_src=twsrc%5Etfw">@FCC</a> net neutrality rule making. 2 million total. ~500K from Russian email addresses. <a href="https://twitter.com/hashtag/sotn2018?src=hash&amp;ref_src=twsrc%5Etfw">#sotn2018</a> <a href="https://t.co/zCUNlssA54">pic.twitter.com/zCUNlssA54</a></p>&mdash; Alex Howard (@digiphile) <a href="https://twitter.com/digiphile/status/958084755605553152?ref_src=twsrc%5Etfw">January 29, 2018</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
--> 

<!--
#### Astroturf 

> TODO
--> 

<!--
A key feature of astroturf lobbying is its covert nature. On December 19, 1995, President Bill Clinton signed into law the Lobbying Disclosure Act of 1995, establishing new registration and reporting requirements for lobbyists working for corporations, charities, and other nonprofit organizations engaged in efforts to influence legislative and executive branch decisions. The 1995 act was the first major legislation on lobbying in nearly 50 years and was designed to provide transparency in the lobbying process. Early drafts of the Lobbying Disclosure Act included provisions requiring the registration of firms engaged in astroturf lobbying and the reporting of the expenditures made on those actions. Those provisions, however, failed to make it out of committee. As the bill's sponsor, Senator Carl Levin, testified before a House committee considering the bill: “Every reference to grassroots lobbying—and even to paid efforts to stimulate artificial grassroots lobbying—has been deleted from the bill…I am personally disappointed that we were unable to do anything to address the issue of a form of grassroots lobbying referred to as astroturf lobbying, in which lobbyists hire professional experts to run phone banks and generate mail in support of their efforts. In my view, these paid, professional astroturf campaigns bear nothing in common with the genuine grassroots activities…I…hope that the House will reconsider the disclosure of such lobbying.
-->



## Reforms 

Can the unwashed masses provide useful information to agencies? My answer is yes. Will this information be biased? Yes, but all information provided by lobbying groups has a bias, the task is to make biases transparent, and reforms could do this. 

1. First, we must dispense with the idea that agencies merely implement the law. The APA provides for public participation because the ideal of direct democracy might affect the important substantive policy made by agencies. Indeed, agencies are often seeking comment on revisions to rules based on authority delegated decades ago. Agency must make policy to satisfy its mandates. The present question is one of process. Calling for greater congressional oversight or presidential control sidesteps the issue--by what process should agencies make policy?  (Indeed, @Potter2019 shows us that agencies often sidestep oversight, making their procedural rules all the more important.)



2. Critics may argue that opening the door wider to petition campaigns lets in biases. Indeed we know that people who opt to participate are disproportionately privileged. In an unequal society, we have unequal participation, but higher barriers to entry only make this worse.  

More problematic is the concern that a well-funded group that typically dominates rulemaking [@Yackee2006JOP] will sponsor astroturf campaigns, thus creating a false impression of public support. This is a real concern. If dark money can secretly drive impressions of support for a policy, the case for expanding participation is weaker. My analysis suggests that this is uncommon.
<!--
The fact that we do not observe it now does not mean it will not occur, but agencies could ... -->

Reforms along these lines have been suggested. @Rauch2016 would make comment periods more like polls. Nationally representative polling may be a good investment for some rules, but we know from polling research that individuals do not always have clearly formed opinions, and much depends on question wording. The reality is that American politics is animated through groups--people rely on organizations they trust to keep them informed and engaged. In classic pluralist fashion, organizations claim to represent segments of the population in rulemaking. <!--Because these organizations... -->

@Raso2020 suggest a similar reform whereby people could "upvote" comments with which they agree. @Raso2020 lament the "mail from the public dumped on the agency’s doorstep" and claim that "upvoting" would "make rulemaking more interactive. The happy result would bring us closer to the deliberative national town meeting." In contrast, I argue that, empirically, mass comment campaigns already act as a poll or upvote. An upvoting feature would thus codify existing dynamic, not fundamentally depart from it. Either way, the possibilities for "deliberation" with the mass public likely exists in the historical push and pull of pressure groups and government institutions over time, not among millions of people upvoting their policy position in a single rulemaking process.

<!--
as others have pointed out 

As the moderator of my class's forum, I can co-sign research on discursive democracy initiatives that realizing transformative discourse is difficult. The ideal of "transformed into something" is laudable, but people are busy, and any barrier to participation will massively reduce participation. Participation already follows a log scale distribution, with most rules receiving no comments--even major rules, on average, receive less than 10. 
-->

### Aims of Reform {-}

**Lower barriers to participation.**

The main barrier to participation in rulemaking is information. Even people with relatively high social capital, like small business owners, rarely participate because they do not know about the opportunity or lack the time necessary to engage. 

> "they might only find out about a proposed regulation when they're presented with one of these mass comments.  And they might not have time to go back and investigate and then write a full comment letter right before the comment period is going to close.  Because there aren't a lot of small business owners who read the Federal Register every day...writing a detailed comment letter is hard work." - Oliver Sherhouse (GSA 2019a, p. 33)

<!--**Increase transparency.**-->

**Reduce the cost of extracting information from comments.** Reformers often highlight the value of linking comments to particular questions or sections of a draft rule. Technology can certainly improve sophisticated debates about a rule's technical provisions. Indeed, sophisticated commentors have adopted track-changes technology to provide marked-up versions of draft rules.

New technologies may provide an even more important role in gleaning political information from the "torrents of email" and "vexing challenge" posed by mass comment campaigns. 

<!--**Gaurd against fraud.**-->

### Parsing the questions {-}

Agencies often specifically ask questions and solicit comments on specific topics in an NPRM. These topics offer an initial structure to allow commenters to self-identify the topics of their comments. The American Bar Association's Section of Administrative Law and Regulatory Practice recommends "technology that would allow agencies to identify categories that commenters could select when submitting comments." To stay open to new ideas, lobbying groups should be allowed to petition the agency to add topics to the menu or ask additional questions. 

For example, agencies may encourage groups to mobilize in support of the groups' answers to the questions that agencies ask. Given past trends, this will likely take the form of petition campaigns, and agencies should have a mechanism to receive those comments as such. 

### Offering answers {-}

Agencies could also lower the bar to participation by posting answers to their questions from different organizations and allow people to co-sign them or disagree with them. This is both easier for participants and requires less work for agencies to interpret where the commenter stands. 

Social media
    engagement may be especially important if agencies implement the
    recommendations of @ACUS2018 that "Agencies should consider using
    social media before or in connection with direct final rulemaking to
    quickly identify whether there are significant or meaningful
    objections" (p. 34).
    
The risk of astroturf is real under any public comment system (including the current one), but transparency requirements can go a long way. Organizations or individuals acting in their professional capacity as organizations (not individuals) should be required to disclose where the money they paid for them to produce their comments came from. Likewise, organizations running campaigns should disclose the sources of funding for the campaigns and how much they spent mobilizing public support. These numbers will provide a helpful denominator for agencies to gauge public enthusiasm.

---


<!--

ACUS Report {-}




#### Increasing transparency and public participation (GSA-2019-02) {-}

On January 30, 2020, the Government Services Administration held a hearing on the topic of mass comments. The three invited speakers represented the National Association of Manufacturers, the Small Business Administration, and MITRE. A federally funded technology research and development. These three guests embody important aspects of how public comment is seen. First, public comment is most often utilized by business groups like NAM ("power users of the regulatory process," as Hedern put it) and thus represents the users for whom public comment technology is designed. NAM does not sponsor mass comment campaigns. Perhaps they have a stake in delegitimizing mass comment campaigns that occasionally mobilized on the opposing side, but the reason they are on this panel is simply that they are the archetypical user. Second, agencies like the Small Business Administration are the ones who must deal with the "challenge" of mass comment campaigns. Third, technology consultants represent the way in which mass comment campaigns are primarily viewed as a technological challenge.

Another important feature of this policy area is its tight-knit epistemic community. As observed by Mr. Hedren:

> "it's a little alarming to me in some respects to see that, looking out into the crowd, I think I know about half of you on a first-name basis. So, we probably need a little bit more fresh blood in this regulatory nerd community." - Patrick Hedren, National Association of Manufacturers.

-->

<!-- 
> And we've very much kind of what, I would consider power users of the regulatory process. We have a clear point of view for the manufacturing sector.  We infrequently weigh in agency actions across the entire federal family, whether they're independent agencies or executive agencies and departments.  So we have quite a lot of experience and exposure to the tools that really underpin the system.  And there's a lot of value in those tools.-->
  

### Gaurding against fraud {-}

As with any form of public participation, fraud merits attention. If organizations submit comments on behalf of people who do not exist or did not consent, this is akin to fraudulent petition signatures or fake constituent letters being sent to Members of Congress. 

**Authentication.** Matt Cutts (acting director of the U.S. Digital Service) suggests CAPTCHAS, email confirmations, and multi-factor authentication. If comments are allowed to be collected by third parties like the Sierra Club, the government can encourage but *may not be able to enforce the use of CAPTCHAS*. Requiring confirmation or authentication by email or phone alone would be a barrier to participation. Requiring both could be prohibitive. 

The most secure approach that allows third parties to gather comments may be to authenticate each comment by asking each commenter to provide an email address or phone number at which to receive a message asking them to confirm the text of their comment. 

Asking for a second interaction with the agency raises the cost of participation but may also make participation a slightly richer experience. <!--(as Dan Walters suggested on Twitter).--> People may be more likely to feel that their voice was heard. Of course, many people will fail to confirm their authenticate their comment, but like mass comments themselves, the number of people willing to take the time to authenticate offers information on the intensity of genuine support. Unauthenticated comments need not be discounted, but authenticated comments may indicate stronger preferences. 

More importantly, authentication guards against identity theft. It is difficult to provide a large number of fake phone numbers, and real phone numbers used fraudulently would likely generate complaints, alerting the agency that the campaign may be engaging in fraud. Again, fraud complaints need not discount an entire campaign. Opponents of a campaign by the Sierra Club, for example, could submit fraudulent comments through their system in order to complain when asked to authenticate and thus cast doubt over the campaign. However, a legitimate campaign will also have a portion that will authenticate, allowing rough estimates of the scale of true support versus fraud. 

Some means of authentication, such as email, maybe slightly more open to fraud than others, like texts, but the benefits to lower barriers to participation may outweigh the greater risk of fraud. 

Because mass comment campaigns include a fairly large number of individuals, especially if the barriers to participation are lower, there are many opportunities to identify fraud of any significant scale, and the stakes of a few fraudulent comments slipping through the cracks are low. 

**Should agencies accept anonymous comments?** There are good reasons to accept technical information from anonymous sources. For example, they may fear retaliation. However, anonymous comments should not be used to infer political information. This distinction supports two tracks with distinct requirements. An agency may want to allow sophisticated anonymous comments to be co-signed by large numbers of authenticated supporters, thus allowing insiders with the necessary knowledge to make sophisticated arguments, but also to put ideas into public and the agency to gauge public reactions to those ideas. 

<!---


# April


FDA 
- used to use interns 
- put comments into an excel
"by hand and I"--"Included the prevalent postcard campaigns."
- "as the number grows, so do the tools."
- "don't see this slowing down anytime soon."
using text analysis to identify topic and theme
- uses contractors 

FDA CONTRACTOR FROM SAS

- main themes/concerns 
- - themes that require a common response
- - new issue or similar to the previous comment
- who are the commenters 
- id fake and mass comments
- text clustering (unsupervised)
- unclear if using plagiarism (seems not, just did it by hand for one comment in the cluster)
- entity extraction
-

# Questions 
- What portion of FDA rules use contractors to process comments? What portion of comments do contractors process?

# Software 

#### Rule revision {-}

Open-source 

GSA GitHub 

#### Comment analysis  {-}

open code 
open source 

Will the code text analysis used be part of the record or otherwise made public? Will it use open-source software?

#### API



<!---



### Existing studies

#### Studies cited by GSA

1. Commentsonthebackgroundinformationprovidedabouttheprogram 
2. Commentsonthevalidityofthestudiesthemselves
3. Comments on other research that the program staff should be aware of


Cary Coglianese, S. S. (2004, November). RECOMMENDATIONS FOR THE DESIGN OF THE FEDERAL DOCKET MANAGEMENT SYSTEM. Retrieved March 2, 2020, from GWIPP WORKING PAPER SERIES: https://gwipp.gwu.edu/sites/g/files/zaxdzs2181/f/downloads/Working_Paper_008 _FedDocket.pdf
Farina, C. R. (2008). Achieving the Potential: The Future of Federal eRulemaking: A Report to Congress and the President. Retrieved March 3, 2020, from Scholarship @Cornell Law: A Digital Repository: https://scholarship.law.cornell.edu/cgi/viewcontent.cgi?article=2505&context=fac pub
Rubin, T. (2018, December 1). REGULATIONS.GOV AND THE FEDERAL DOCKET MANAGEMENT SYSTEM. Retrieved March 3, 2020, from Administrative Conference of the United States: https://www.acus.gov/sites/default/files/documents/Regulations.gov%20Report% 20FINAL%2012%203%202018.pdf
The Federal Rulemaking Process: An Overview. (2013, June 17). Retrieved March 3, 2020, from EveryCRSreport.com: https://www.everycrsreport.com/reports/RL32240.html

--->