# Conclusion {#book-conclusion}

The legitimacy of bureaucratic policymaking is said to depend on the premise that rulemaking provides for public voice [@Croley2003, @Rosenbloom2003]. Yet, to date, normative debates about the value of public comment processes have had little systematic empirical knowledge to draw upon. If input solicited from ordinary people has little effect on policy outcomes, directly or indirectly, it may be best understood as providing a veneer of democratic legitimacy on an essentially technocratic or elite-driven process. Worse, if public pressure campaigns are largely astroturf---misleading impressions of public support sponsored by narrow private interests---it could further tilt the scales of the policy process toward concentrated economic power.

In this chapter, I first discuss the implications of my theory and findings for the study of bureaucratic policymaking. Section \@ref(future) then suggests some avenues for future research. Section \@ref(policy) concludes with implications for current debates over how to think about the value of public participation and what those values---combined with the findings of this dissertation---imply for policy reforms. 


## Findings

This dissertation has made several steps toward better understanding public engagement in bureaucratic policymaking.

Chapter \@ref(whymail) set out a theory of why groups participate and offer the most comprehensive assessment to date of participation in bureaucratic policymaking. In contrast to much of the debate over the value that the lay public may or may not provide as individuals, I argue that engaging in federal policymaking is almost exclusively a collective affair. Supporting this argument, I find that most civic participation in bureaucratic policymaking results from pressure campaigns from advocacy groups. Given the barriers to even knowing about, much less engaging in bureaucratic policymaking [@Kerwin2011], it is unsurprising that people who participate are almost rarely alone. 

My theory and evidence for *mobilized* public engagement have implications for scholarship. First, we learn little by comparing form letters to comments written by lawyers  [@Seifter2016UCLA, pg. 1313]; instead, we must study these as two tactics used by the same organizations and lobbying coalitions. Second, public participation is *mediated* through organizations; studying civic participation means studying the organizations that mobilize people. While I focus on public pressure campaigns targeting bureaucratic policymaking, many of the theories and methods that I advance should be well-suited to study other situations in which organizations mobilize public pressure.

Public pressure campaigns targeting agency rulemaking in the U.S. are overwhelmingly sponsored by public interest groups. Compared to business groups, I theorize that public interest groups more often have incentives to expand the scope of the conflict, and I show that they more often do. However, mobilizing is also a tactic that requires resources, leading the vast majority of mobilizing to be led by a few national advocacy organizations. The resources required to lobbying in national policy means that a small set of large organizations often mobilize other organizations with less capacity for policy advocacy (as documented by @Nelson2012, @English2019, and @Dwidar2021APSR). I show that these same large advocacy organizations mobilize almost all public participation. The implication is that lobbying coalitions are the proper unit of analysis for most studies of public participation or interest group influence in bureaucratic policymaking---not individuals or even organizations. While studying lobbying coalitions is more difficult than studying individual organizations, this dissertation has developed theories and methods to systematically study the composition and influence of lobbying coalitions across institutions and over time.

Chapter \@ref(influence) builds on my theory of why groups opt to mobilize public pressure to include both direct and indirect pathways of policy influence. Both pathways are contingent on a number of institutional features related to how bureaucratic institutions process incoming information (more on this below). It is difficult to assess the direct relationship between public pressure and lobbying success because the policies that groups target are correlated with their likelihood of success. My theory of why groups mobilize, set out in Chapter \@ref(whymail), predicts that private interest groups are more likely to mobilize public pressure only when it is likely to help their cause. And indeed, the results presented in \@ref(influence-results) show that pressure campaigns sponsored by private interest groups have a higher correlation with lobbying success. This could be evidence that public pressure campaigns sponsored by narrow private interests are more influential---perhaps because they are more surprising, causing agency officials to update their beliefs about public opinion. However, the confounded and endogenous relationship between who chooses to launch a pressure campaign and who wins makes it difficult to draw firm conclusions about the direct effects of public pressure campaigns from these data. 

My analysis in Chapter \@ref(influence) suggests that public pressure campaigns are most likely to influence bureaucratic policymaking indirectly by attracting the attention of members of Congress. 
The scale of public attention and pressure campaigns, in particular, are highly correlated with involvement from members of Congress, and coalitions with more members of Congress are more likely to win. While both pressure campaigns and legislator engagement may be driven by the salience of the policy process, increasing the salience of the policy process is often the main goal and a plausible effect of pressure campaigns. (more on this in Appendix \@ref(formal-app))). Thus, while members of Congress may also be driven to engage in rulemaking by related factors like media coverage, public pressure campaigns are almost certainly very intentionally pushing those other levers of power while simultaneously mobilizing public participation in the policy process. If we view mass comment campaigns as a proxy for a coalition's broader lobbying efforts to raise awareness and expand the scope of the conflict, we can more confidently say that pressure campaigns likely affect the behavior of members of Congress. 

Chapter \@ref(ej) investigates another potential mechanism of direct influence: claims about distributive justice. My analysis suggests that both pressure campaigns and minority activism can affect the discourse of policymaking, including the preambles to policy documents where agencies justify their proposed and final policies. When commenters raise distributive justice concerns, agencies are much more likely to address these concerns. The more people who raise such concerns, the more likely it is that agencies address them. Raising the overall level of public attention can have a similar effect as raising specific concerns. Agencies are more likely to add a discussion of how policies address environmental justice when comments raise justice concerns *or* they receive large numbers of comments. This may be related to the fact that courts are more likely to uphold policies with high levels of participation [@judgelord2016MPSA].
In contrast, when an agency already addressed environmental justice in their proposed rule, rules with more comments were less likely to change, supporting the hypotheses that more salient rules may be harder to change because the agency has anticipated public scrutiny. Their position stated in the draft is more likely to be the position of the final rule.

If I had found that most public comments were the result of astroturf campaigns, the implications would be clear: public comment periods would be merely a veneer for economic power. Conversely, if I had found that public comments were mobilized by a nationally representative set of organizations and that they were highly effective in reducing the bias toward businesses in rulemaking, the implications would also be clear: public comment periods would democratize policy outcomes and should be expanded. 

Instead, my findings are mixed. Public pressure campaigns do systematically counter the narrow private interests that usually dominate bureaucratic policymaking, but it is not clear how effective they are. Specifically, it is not clear that they are more effective than pursuing representation more indirectly through the legislative branch. The number of allies in Congress that a coalition mobilizes is the only clear predictor of lobbying success that lobbying coalitions have any control over. 

The few organizations that dominate public pressure mobilizing are---for the most part---not the "usual suspects" (few of them lobby as frequently as the Chamber of Commerce or the American Petroleum Institute). However, the breadth of the constituency represented by those organizations is unclear. On the one hand, they regularly mobilize millions of genuine supporters. On the other hand, the interests are concentrated on certain policy issues (especially environmental issues) and not others (for example, transportation safety). Even within the policy areas they operate, it is not clear how well they represent the people for whom they claim to speak. 

These findings raise as many questions as they answer. The next section briefly discusses a few of the many opportunities for future research to build on my analysis.