## Re-thinking Public Participation in Bureaucratic Policymaking


One of the main contributions of this dissertation has been to clarify a way of thinking about and studying public comments. 
In light of the empirical evidence in the previous chapters, I now revisit some of the dominant ways of thinking about public comments among scholars and practitioners who are currently debating reforms to participatory processes. I start with a sketch of the various positions staked out by administrative law scholars (who have done nearly all of the work on this topic), each rooted in different theories of democracy. I then discuss several specific challenges and proposed reforms to the policy process. <!--Finally, I extend -->

I conclude that reforms underway in U.S. federal institutions that solicit, collect, and process comments are already heading toward enhancing participation and the quality of political information that it generates. However, certain additional reforms, particularly those that call for more transparency of mobilizing groups, would further improve the political information available to agencies and outside observers. I have argued that we should see civic participation in bureaucratic policymaking as a collective activity mediated by mobilizing organizations. This perspective focuses our attention on advocacy organizations: who they are, who they represent, who they are mobilizing, and how they are mobilizing---all potential targets for research and policy reform. Specifically, this perspective emphasizes reforms that require transparency from lobbying organizations. 


### Public Pressure Campaigns as Petitions

Understanding mass commenting as a form of petitioning, as I have argued, runs against how scholars often discuss it. With a few notable exceptions [e.g., @Cuellar2005; @Mendelson2011; @Rauch2016], legal scholars often imply that mass commenting is misguided and potentially harmful spam of the technocratic process. In a report submitted as a comment on "Public Forum on the eRulemaking Initiative's www.Regulations.gov Web site and the Development of the Federal Docket Management System" about reforming the public comment process, Stewart Shulman summarizes the concern: 

> Many fear a surging wave of electronic mass submissions will overwhelm and thus delay agencies with limited resources. Furthermore, some warn us that electronic rulemaking may already have instantiated a sense that rulemaking decisions are akin to a plebiscite. (EPA-HQ-OEI-2004-0002-0015)



In response to public pressure campaigns, agency officials and observers often assert that comments are not votes and rulemaking is not a plebiscite [@Mendelson2011].
At the same time, agencies frequently do tally up comments on each side. In a 2008 rule regulating border crossing by private aircraft, The U.S. Customs and Border Patrol (CBP) cited the scale of public engagement as providing information on "public sentiment."

> based on the ample number of comments received by the end of the original comment period, CBP believed that public sentiment was accurately captured. ([CBP-E8-26621/p-61](https://www.federalregister.gov/d/E8-26621/p-61))

In the preamble to the 2015 Waters of the United States Rule, EPA evoked both majoritarian and pluralist justifications:

> This final rule reflects the over 1 million public comments on the proposal, the substantial majority of which supported the proposed rule, as well as input provided through the agencies' extensive public outreach effort, which included over 400 meetings nationwide with states, small businesses, farmers, academics, miners, energy companies, counties, municipalities, environmental organizations, other federal agencies, and many others. ([2015-13435/p-67](https://www.federalregister.gov/d/2015-13435/p-67))

EPA Administrator Gina McCarthy testified that EPA "received over one million comments, and 87.1 percent of those comments...are supportive of this rule" [@Lipton2015].
When the EPA issued a new rule rolling back the definition of Waters of the United States under the Trump administration, the preamble noted that there were "a number of comments" in favor of the new definition but "a significant number of comments" in favor of the 2015 definition ([2020-02500/p-231](https://www.federalregister.gov/d/2020-02500/p-231). While not going so far as to explicitly state that a supermajority of commenters opposed the new policy, it is still remarkable that the agency would choose to note quantitative opposition to the policy. For some reason, this political information merited attention.

Agencies also regularly refer to form comments as petitions. When the Bureau of Land Management (BLM) received 6,948 identical emails that did not cite an organization, BLM officials (or consultants) labeled these comments a "Pro Fracking Petition" ([LM-2013-0002-5720](https://www.regulations.gov/comment/BLM-2013-0002-5720)). A nearly identical comment was signed by "Oil and Gas industry individuals" ([BLM-2013-0002-5688](https://www.regulations.gov/comment/BLM-2013-0002-5688)). Another batch of 1,289 nearly identical emails submitted through the social networking website Care2.org was labeled "Anti Fracking Petition" ([BLM-2013-0002-5721](https://www.regulations.gov/comment/BLM-2013-0002-5721))

The organizations running public pressure campaigns are even more explicit that they consider mass comments to be petition signatures, frequently citing mass comments as "Letters in support of [our organization's] Comments" ([NOAA-NMFS-2012-0059-0023](https://www.regulations.gov/comment/NOAA-NMFS-2012-0059-0023)) or a "petition from World Wildlife Fund-US (WWF-US), signed by 271,893 WWF-US supporters" ([BOEM-2016-0003-2556](https://www.regulations.gov/comment/BOEM-2016-0003-2556)).
The files containing comments collected by organizations are often named "signatures.pdf." Clearly, agencies and organizations already consider mass comment campaigns to be a form of petitioning.

How does this understanding of public pressure campaigns as petitions affect the debate over their value? Does a focus on political information affect the debate over the value of public participation in bureaucratic policymaking? In the next subsection, I sketch out some of the normative positions <!--staked out by scholars active --> in debates over how to reform the rulemaking process. I then comment on several proposed reforms in light of the theory and findings presented in this dissertation. 

###  The Roots of the Debate

Normative scholars vary significantly in both the value they place on political information and the extent to which they believe that meaningfully engaging large numbers of people is possible. I group those concerned with reforming the public comment process into five camps: (1) Participatory democracy optimists, (2) Regulatory democracy reformers, (3) Pluralist reformers, (4) Rational pluralists, and (5) Skeptics. 

#### Participatory democracy optimists {-}

Optimists see notice and comment as the "purest example of participatory democracy in actual American governance" [@Herz2016, p. 1]. The process is technically open to anyone with an opinion to offer, and agencies are, to an extent, required to respond to substantive ideas. This optimism is rooted in a volunteerist idea of democracy and a value for inclusive and substantive discourse. In its optimism, these observers often assume that those who "ought" to be included do not have large barriers beyond the formal rules of the institution. It also assumes that meaningful discourse among those who participate is possible and likely to occur. 

#### Regulatory democracy reformers {-}

A related camp is slightly less rosy about the current institutions and practices but is nevertheless optimistic that reforms can at least improve the quality of discourse, and thus policy. For these scholars, democracy is more a function of procedure than inclusion. <!--Comments should offer "issues and contributions, information and reasons." -->
@Cuellar2014 <!--and @Jonson2013-->
argues that rulemaking could be more discursive. @Mendelson2011 found that agencies often discard non-technical comments but argues that they should not because mass comments contain valuable information. For this camp, the quality of the public debate is more important than the total number of people, their affiliations, or their biases. They emphasize the transformative power of discourse. 

#### Pluralist reformers {-}

A different brand of reformer focuses less on discourse and more on interest group representation. Reform-oriented scholars building on pluralist ideas of representation argue that lobbying organizations should be required to disclose their membership, funding, and decision-making processes [@Seifter2016UCLA]. In this view, organized groups---not individuals---are the central actors in public comment processes. However, because agencies often lack information about groups, it is difficult to know how well they represent the people they claim to. Interest groups' faithful representation of their members is crucial to pluralist ideas of democracy. 


#### Rational pluralists {-}

Another group of scholars focuses on the benefits of organized interest groups and experts that can provide credible technical information. In this view, random or self-selecting members of the general public are not helpful or appropriate participants in the policy process. "The goal of e-rulemaking is to more fully capture such credible, specific, and relevant information, not to solicit the views of random, self-nominating members of the public" [@Herz2016]. Speaking on the topic of mass comment campaigns, Oliver Sherouse, a regulatory economist at the Small Business Administration, expressed the same sentiment: 

> It's worth remembering why we have a public comment process in the first place, which is that the public has knowledge that regulators do not have and that they need to do their jobs well...how do the poor quality mass comments affect small businesses in the comment process? The most obvious problem would be if legitimate small business concerns are just lost in the flood" [@GSA2019, pp. 31-32].

Sharehouse raised an additional concern that mass-comment campaigns might distract people from writing their own, more informative comments. While recognizing that "not everyone who does not sign onto that kind of [mass] comment would be willing to write a high-quality one," the tradeoff of a few "quality" comments for many "poor quality" comments is worthwhile. [@GSA2019, p. 32] This perspective is open to limited public participation, but only certain concerns are legitimate, for example, the opinions of client industries and new technical information on which to base rational analyses.

<!-- TRY TO WORK THIS IN
However, Sherouse was also wary about completely dismissing mass comments. 
> "A good point is not less of a good point because 10,000 people happen to agree with it." (GSA 2019a, p. 32) This suggests that even some rational pluralists can see the potential benefits of allowing at least some public comments, even if they are wary of the current system.
-->

#### Skeptics {-}

The most skeptical camp goes even further, arguing that open solicitations to the general public should be abolished. From the observation that the lay public usually has little to offer a technocratic process, they conclude that it is a waste of resources to solicit opinions that won't be counted. More importantly, this camp holds civic republican ideas about the proper relationship between citizens and the state. It defines a democratic process as one that follows as straightly as possible from the elected branches. The goal is to de-politicize bureaucratic policymaking. 



### Reforming the Policy Process {#policy}

The theory and findings in this dissertation are most compatible with what I have called the "pluralist reformer" project. While the discursive ideals of "regulatory democracy" optimists and reformers may be possible (at least at a small scale), their goal of including the lay public in a more discursive policy process is very far from how I have shown that civic participation in bureaucratic policymaking currently occurs. The rational pluralist camp either ignores the value of what I call political information or dismisses it as a normative ill. 

The "pluralist reformer" perspective aligns with the theory and results presented in Chapter \@ref(whymail). Interest group organizations are key intermediaries between the public and policymakers. Some make dubious claims about whom they represent. Other organizations organize mass comment campaigns, providing more concrete evidence of a supportive constituency.


**Transparency** More challenging is the concern that narrow, concentrated interests that typically dominate rulemaking will sponsor astroturf campaigns, thus creating a false impression of public support. This is a real concern. If dark money can secretly create impressions of support for a policy, the case for expanding participation is weaker. My analysis suggests that this is less common than genuine participation, but I did uncover examples of astroturf and fraud. 

As with any form of public participation, fraud merits attention. Organizations submitting comments on behalf of people who do not exist or did not consent is akin to fraudulent petition signatures or fake constituent letters being sent to members of Congress. 

Reforms requiring more transparency in the process by which organizations represent segments of society, like those proposed by @Seifter2016UCLA, would help guard against astroturf and fraud. 
Transparency also clarifies political information, making it more useful both to agencies and outside observers. To the extent that participation is mobilized by organizations, agencies can ask these organizations to be transparent about their sources of funding.

However, reforms requiring groups to disclose information about their funding and membership only go partway to address groups' representational claims, which often extend far beyond their membership. Such claims are more difficult to assess. However, similar reforms could require disclosure of the funding and methods by which organizations gather petition signatures.  Organizations or individuals acting in their professional capacity as organizations (not as individuals) could be required to disclose the source of the money that them to produce their comments. Likewise, organizations running campaigns could be required to disclose the sources of funding for the campaigns and how much they spent mobilizing public support. These numbers will provide a helpful denominator for agencies to gauge public enthusiasm and other kinds of political information that public pressure campaigns provide.
More information about petition signers could help clarify which segments of the public are participating. 
As discussed in Chapter \@ref(ej), the people that organizations claim to represent are not always the people who sign their petitions.


**Authentication.** <!--Matt Cutts (acting director of the U.S. Digital Service) suggests CAPTCHAS, email confirmations, and multi-factor authentication.--> If comments are allowed to be collected by third parties like the Sierra Club (recall Figure \@ref(fig:sierra)), the government can encourage but may not be able to enforce authentication tools like CAPTCHA (Completely Automated Public Turing test to tell Computers and Humans Apart). Organizations that upload large batches of comments already go through a verification process, but this does not address the veracity of their petition signatures. Requiring confirmation or authentication by email or phone alone would be a barrier to participation. 

The most secure approach that allows third parties to gather comments may be to authenticate a sample of comments by asking each commenter to provide an email address or phone number at which to receive a message asking them to confirm the text of their comment. 
Asking for a second interaction with the agency raises the cost of participation but may also make participation a slightly richer experience. <!--(as Dan Walters suggested on Twitter).--> People may be more likely to feel that their voices were heard. Of course, many people will fail to authenticate their comments, but like mass comments themselves, the number of people willing to take the time to authenticate offers information on the intensity of genuine support. Unauthenticated comments need not be discounted, but authenticated comments may indicate stronger preferences. 

More importantly, authentication guards against identity theft---fake political information. It is difficult to provide a large number of fake phone numbers, and real phone numbers used fraudulently may generate complaints, alerting the agency that the campaign may be engaging in fraud. Again, fraud complaints need not discount an entire campaign. Opponents of a campaign by the Sierra Club, for example, could submit fraudulent comments through their system in order to complain when asked to authenticate and thus cast doubt over the campaign. However, a legitimate campaign will also have a portion that will authenticate, allowing rough estimates of the scale of true support versus fraud. 

Some means of authentication, such as email, may be slightly more open to fraud than others, like texts, but the benefits of lower barriers to participation may outweigh the greater risk of fraud. 
Because mass comment campaigns include a fairly large number of individuals, especially if the barriers to participation are lower, there are many opportunities to identify fraud of any significant scale, and the stakes of a few fraudulent comments slipping through the cracks are low. 

<!--
**Should agencies accept anonymous comments?** There are good reasons to accept technical information from anonymous sources. For example, they may fear retaliation. However, anonymous comments should not be used to infer political information. This distinction supports two tracks with distinct requirements. An agency may want to allow sophisticated anonymous comments to be co-signed by large numbers of authenticated supporters, thus allowing insiders with the necessary knowledge to make sophisticated arguments, but also to put ideas into public and the agency to gauge public reactions to those ideas. 

-->

**Lower Barriers to Participation** A second facet of reform may center around increasing access, both for organizations and the people they mobilize to participate. 


Is it possible to broaden civic participation in bureaucratic policymaking?
Is it worthwhile? Many assume not, but my analysis offers some hope. As I show in Chapter \@ref(whymail), more participation generally means more diverse and public-spirited voices at the table. As I show in Chapter \@ref(influence), more public participation is related to more oversight from members of Congress (in part because they receive copies of public comments from their constituents). As I show in Chapter \@ref(ej), agencies respond when people raise new concerns, especially when a large number of people raise them. At the same time, there is little evidence that mobilizing more people has an impact on the outcomes of particular policy fights. The coalition with the most comments is not necessarily more likely to win. It is possible that narrow private interests are able to strengthen their cases by showing evidence of broader public support. However, the correlation between pressure campaigns backing business interests and lobbying success could also simply be the result of selection effects: public interest groups have incentives to mobilize on policy fights even when they are likely to lose, whereas private interest groups do not. 




Critics may argue that opening the door wider to petition campaigns lets in biases. Will this information be biased? Yes, but all information provided by lobbying organizations has a bias. Indeed we know that people who opt to participate are disproportionately privileged. An unequal society leads to unequal participation, but higher barriers to entry only make this worse.  



Several recent reform proposals align with viewing mass comments as a form of petitioning. @Rauch2016 suggests making comment periods more like polls. Nationally representative polling may be a good investment in political information for some rules, but we know from polling research that individuals do not always have clearly formed opinions, and much depends on question-wording. The reality is that American politics is animated through groups---people rely on organizations they trust to keep them informed and engaged. <!--In classic pluralist fashion, organizations claim to represent segments of the population in rulemaking. <!--Because these organizations... -->
@Raso2020 suggest a similar reform whereby people could "upvote" comments with which they agree. @Raso2020 lament the "mail from the public dumped on the agency’s doorstep" and claim that "upvoting" would "make rulemaking more interactive. The happy result would bring us closer to the deliberative national town meeting." In contrast, I argue that, empirically, mass comment campaigns already act as a poll or upvote. An upvoting feature would thus codify the existing dynamic, not fundamentally depart from it. Either way, the possibilities for "deliberation" with the mass public likely exist in the historical push and pull of pressure groups and government institutions over time, not among millions of people upvoting their policy position in a single rulemaking process.


**Reducing the Cost of Providing and Processing** Information Reformers often highlight the value of linking comments to particular questions or sections of a draft rule. Technology can certainly improve sophisticated debates about a rule's technical provisions. Indeed, sophisticated commenters have adopted track-changes technology to provide marked-up versions of draft rules.
New technologies may provide an even more important role in gleaning political information from the "torrents of email" generated by mass comment campaigns. 

**Parsing the questions** Agencies often specifically ask questions and solicit comments on specific topics in a proposed rule. These topics offer an initial structure to allow commenters to self-identify the topics of their comments. The American Bar Association's Section of Administrative Law and Regulatory Practice recommends "technology that would allow agencies to identify categories that commenters could select when submitting comments." To stay open to new ideas, lobbying organizations should be allowed to petition the agency to add topics to the menu or ask additional questions. 

For example, agencies may encourage groups to mobilize in support of the groups' answers to the questions that agencies ask. Given past trends, this will likely take the form of petition campaigns, and agencies should have mechanisms to receive those comments as such. <!--and they are -->

**Offering Answers** Agencies could also lower the bar to participation by posting answers to their questions from different organizations and allowing people to co-sign or disagree with them. This is both easier for participants and requires less work for agencies to interpret where the commenter stands. 





## Final Remarks

Can the masses provide useful information to policymakers? If the theory set out in this dissertation is correct, they can, but the extent to which U.S. federal agencies currently have the capacity to process and use this information is unclear. 
Reforms could make biases more transparent and broaden the number and diversity of groups that are able to participate.

<!-- In this way, notice and comment could make rulemaking---which is actually how a bazillion laws are made---more representative of our great democracy, a democracy where that banner still waves while bald eagles fly overhead and a McDonald’s sign beckons from a distance to bureaucrats just trying to do the will of “We the People.” Give these bureaucrats better comments. Then, let them break for lunch. --> 
