# Acknowledgements

Anne Judge Bob Lord

Kristy fullertion Rico

committee 
Susan Yackee (chair), Eleanor Powell, Alex Tahk, David Weimer, Miriam Seifter

participants in
the 2019 and 2021 American Politics Workships at UW-Madison, especially Mike DeCresenzo, Dan Walters, and Marcy Shei, 
the 2020 American Political Economy Summer School, especially Alex Hertel-Fernandez, the 2020 APSA Dissertation Workshop Daniel Mallinson, Darrell Lovell, Sam Zuhlke, Elizabeth Dorssom, Nathalie Mendez, Isaac Pollert, Mark Bento,
the Southern Political Science Conference, especially Brian Libgober, 
Comments from
Barry Burden, 
Scott Straus,
David Greenwood-Sanchez, 
Michael Decrescenzo,
Dmitry Kofanov,
Michael Promisel,
Ben Power,
Micah Dillard,
Participatans in the Association of Environmental Studies and Sciences,

asdf ad and participats in the APSA Writing Workshop 

collegues
especially Mike DeCresenzo on Chapter 1 and Marcy Shieh on chapter 4 Dan Walters

 Association of Environmental Studies and Sciences and Southern Political Science Conference

awh 
marcy 
barry 
cannon 
scott 

My cohort 


Friends and mentors, esepecially  who took time to talk though the ideas and solve problems: Wendy Li, Steve Rashin, Brian Libgober, Dan Carpenter, John Hoffman, Adeline Lo, and Ben Cashore


family 

friends 

Wendy John Hoffman

Emma and John and Karolina Rico for hosting a very boring housejust 

The analysis in chapter 3 is only possible due to the hard work of an top-notch team of research assistants: Lucy McNeil, Anastasie Ndahayo, Hailey Patel, Hope Karnopp, Jackson Mozena, Julia Derzay, Maggie Claire Nead, Max Linse, Megan Gmelich, Samiha Bhushan.

Funding from National Science Foundation, American Political Science Association, the La Follette Fellowship from University of Wisconsin La Follette School of Public Affairs, and the Summer Research Initiative Research Award University of Wisconsin-Madison's Political Science Department.