--- 
title: "Public Pressure Campaigns and Bureaucratic Policymaking"
author: "Devin Judge-Lord"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: memoir
classoption: oneside
fontsize: 12pt
geometry: "left = 1.25in, right = 1.25in, top = 1.25in, bottom = 1.25in"
bibliography: "assets/dissertation.bib"
biblio-style: "assets/apsr.bst"
link-citations: yes
github-repo: https://github.com/judgelord/dissertation
description: "Draft"
always_allow_html: true
---

```{r setup, echo = FALSE, include = FALSE}
source(here::here("code", "setup.R"))
```

  \listoftables
  
  \listoffigures
  
# List of Key  Terms {-}

- **Astroturf** campaigns are a form of outside lobbying intended to create a deceptive appearance of public support. The group organizing the campaign is only doing so because they are being paid. The individuals mobilized are often either deceived (e.g., intentionally misled about the policy or its likely effects) or financially incentivized to participate. In the extreme, astroturf campaigns may use the names of fake or non-consenting individuals. In contrast, a more grassroots campaign may also require funding, but groups would choose to use resources for such a campaign even without the quid pro quo, and individuals are mobilized based on some pre-existing interest or belief. While grassroots campaigns may involve simplification, spin, and even mild deception, it is not decisive. 

- A **coalition** is a group of actors pursuing the same aims in the same policy fight. Because coordination is difficult to measure, my empirical definition includes individuals and organizations that identify themselves as coordinated and advocate for the same policy outcomes regardless of overt coordination. 

- **Going public** describes the choice to pursue an "outside" strategy to influence policy outcomes that aims to expand the scope of conflict and involve more actors than would be involved if the lobbying organization only employed an "inside" lobbying strategy focused on the policymakers.

- **Lobbying influence** implies a causal effect between an effort to influence policy and a policy outcome.

- **Lobbying success** describes a situation where a group that sought to influence policy got the outcome they sought but does not imply a causal relationship between their effort and the policy outcome.

- A **mass commenting campaign** is a type of public pressure campaign focused on mobilizing public comments. Such comments are "mass comments." For analytic purposes, I define a mass comment in Chapter \@ref(why-methods) as any comment with 100 identical copies or uploaded in a batch of 100 or more by the same organization.

- A **membership organization** is a type of organization formed to serve the interests of a defined membership. Membership organizations may serve their members' narrow material interests or their members' broader visions of the public interest. Some membership organizations are more directly governed by their members than others.

- **mobilizing groups/organizations** recruit people to take an action (e.g., to sign a petition or submit a public comment).

- An **organization** is usually incorporated as a business, government, or nonprofit. Public comments *from* organizations represent the position of the organization as an incorporated entity. I only consider a comment to be on behalf of an organization if it claims to represent the organization. An employee using letterhead is insufficient. Letters from elected officials are only considered to represent their institution if they are in a position to do so (e.g., a governor, attorney general, or committee chair) and claim to do so.

- A **public interest group** is a type of organization that *primarily* advocates for some vision of the public good, not the private material interest of its owners or members. Policy conflicts may involve competing visions of the public interest and thus multiple public interest group coalitions.

- A **public pressure campaign** is an effort to influence policy by mobilizing a segment of the public to pay attention to and express their opinions to decision-makers. It can be an astroturf campaign or grassroots campaign on behalf of public or private intersts.

- **Responsiveness** is observable attention that government officials pay to public input. This can be either discursive influence (similar to what [@Balla2020] call "proceedural responsiveness") or substantive policy influence.



# Citations to Primary Documents  {-}

I extensively cite public records, including policy documents and public comments. Most of these documents have government-issued identification numbers. Citations to documents published in the Federal Register include an agency acronym, the year the document was published, and a document number (usually five digits, e.g., "CFPB-2020-14935"). If citing a specific paragraph, the citation will appear as "CFPB-2020-14935/p-134." Federal Register documents can be accessed by appending "https://www.federalregister.gov/d/" to the id number, for example, "https://www.federalregister.gov/d/2020-14935/p-134". Citations to documents posted to regulations.gov begin with a docket number, including an agency acronym and the year the rulemaking docket began, followed by a unique document number (e.g., IRS-2016-0015-0125).

\newpage 


# Timeline {-} 

- April 15 - All dissertation writing in one document, with placeholder sections describing "to-do" tasks  
- April 30 - Draft analyses sent to Alex and Dave using samples of real data  
- May 15 - 100% versions of 1st and 3rd empirical chapters  
- May 30 - 100% versions of intro and conclusion  
- June 13 - Mostly complete draft, including 2nd empirical chapter  
- June 30 - Revised complete draft  
- July 16 - Final manuscript  

 # TODO List
 
 Overall

- [ ] Review more political science literature in intro, Chapter 2, and Chapter 3

- [ ] Update book outline
 
- [ ] Walk through theoretical model step-by-step in each chapter

Chapter 1:

- [ ] Redo figures for chapter 1 with new data

- [ ] Rewrite chapter 1 to better introduce data and theories

Chapter 2:   

- [ ] Final pass of intro and theory sections to align with the "public interest or astroturf?" frame

- [ ] Rewrite data, methods, and conclusion of chapter 2 to align with that frame

Chapter 3:  

- [ ] Finish integrating the middle two empirical chapters into one chapter that will address both the participation of members of congress in rulemaking and the relationship between mass commenting and lobbying success.

- [ ] Walkthrough theory and model, exp. direct pathway 

- [ ] Update hand-coded analysis with non-mass comment sample of rules

- [ ] Add section on validation of automated methods

Chapter 4: minor to-do list here: https://judgelord.github.io/dissertation/ej-appendix#TODO

- [ ] Add coalition size figures 

Chapter 5:  

- [ ] Major rewrite in light of findings

\newpage

# Introduction {-}


Does civic engagement through public pressure campaigns affect agency rulemaking? I examine who participates in public pressure campaigns and why, whether they affect congressional oversight, and whether they affect policy. Answering these questions informs our understanding of bureaucratic politics and interest group lobbying, organizing, and mobilizing tactics. If ordinary people have a voice in bureaucratic policymaking, I argue, it is through public pressure campaigns. Thus, understanding the nature and effects of these campaigns is key to understanding modern democracy. 