---
# date: "`r format(Sys.time(), '%B %d, %Y')`"
# fontsize: 12pt
# mainfont: times
# geometry: margin = 1in
bibliography:  mendeley.bib
biblio-style: apa
citecolor: black
output: #word_document
  bookdown::pdf_document2:
    latex_engine: pdflatex
    keep_tex: true
    template: article-template.tex
    toc: false
    fig_caption: true
    citation_package: natbib
spacing: doublespacing
#endnotes: true
title: "Do Public Pressure Campaigns Influence Bureaucratic Policymaking?"
author: 
- name: Devin Judge-Lord
  affiliation: University of Wisconsin-Madison

abstract: "Do public pressure campaigns affect policies made by unelected bureaucrats? In this article, I develop several measures of lobbying success and corresponding tests of whether public pressure campaings increase lobbying success. I then theorize mechanisms by which mass public engagment may affect policy. Each involves a distinct type of information revealed to decisionmakers."
---



\newpage

\input{intro.tex}


# Methods

To illustrate how I create these variables, consider two such cases:

#### Waters of the United States

In responce to litigation over which waters were protectected by the Clean Water Act, the Environmental Protection Agency and Army Corp of Engineers proposed a rule based on a legal theory articulated by Justice Kennedy, which was more expansive than Justice Scalia's. 
An Attorney for the Natural Resources Defense Council submitted a 69-page highly technical comment "on behalf of the Natural Resources Defense Council..., the Sierra Club, the Conservation Law Foundation, the League of Conservation Voters, Clean Water Action, and Environment America" supporting the proposed rule:

> "we strongly support EPA’s and the Corps’ efforts to clarify which waters are protected by the Clean Water Act. We urge the agencies to strengthen the proposal and move quickly to finalize it..." 

I coded this as support for the rule change, specifically not going far enough. I also coded it as requesting speedy publication. NRDC makes four substantive requests: one about retaining language in the proposed rule ("proposed protections for tributaries and adjacent waters... must be included in the final rule") and three proposed changes ("we describe three key aspects of the rule that must be strengthened").^[These three aspects are: (1) "The Rule Should Categorically Protect Certain “Other Waters” including Vernal Pools, Pocosins, Sinkhole Wetlands, Rainwater Basin Wetlands, Sand Hills Wetlands, Playa Lakes, Interdunal Wetlands, Carolina and Delmarva Bays, and Other Coastal Plain Depressional Wetlands, and Prairie Potholes. Furthermore, "Other 'Isolated' Waters Substantially Affect Interstate Commerce and Should be Categorically Protected Under the Agencies’ Commerce Clause Authority." (2) "The Rule Should Not Exempt Ditches Without a Scientific Basis" (3) "The Rule Should Limit the Current Exemption for Waste Treatment Systems
"] These demands provide specific key words and phrases to search the change in rule text. 

A coalition of 15 environmental organizations mobilized over 944,000 comments, over half (518,963) were mobilized by the four above organizations: 2421,641 by Environment America, 108,076 by NRDC, 101,496 by clean water action, and 67,750 by the Sierra Club. Other coalition partners included EarthJustice (99,973 comments) and Organizing for Action (formerly president Obama's campaign organization, 69,369 comments). This is the the upper tail end of the distribution. This coalition made sophisticated recomendations and mobilized a million people.

The final rule moved in the the direction requested by this coalition, but to a lesser extent than requested--what I code as "some desired changs."" As NRDC et al. requested, the final rule retained the language protecting tributaries and adjacent waters and added some protections for "other waters" like prarie potholes and vernal pools, but EPA did not alter the exemptions for ditches and waste treatement systems. 

For this coalition, the dependent variable, *coalitions success* is 1, *coalition size* is 15, *business coalition* is 0, *comment length* is 69/88, `r round(69/88,2)`, and *log comments* is log(943,931), `r round(log(943931), 2)`.

#### 2009 Fine Particle National Ambient Air Quality Standards

In 2008, the EPA proposed a rule expanding air quality protections. Because measuring small particles of air pollution was once difficult, measurments of large particulates were allowed as a surragate measure for fine particles under EPA's 1977 PM10 Surrogate Policy. EPA proposed eliminating this policy, thus requring regulated entities and state regulators to measure and enforce limits on much finer particles of air pollution. 

EPA received 163 comments on the rule, 129 from businesses, business associations such as the American Petrolium Institute and The Chamber of Commerce, and state regulators that opposed the rule, requesting that it be withdrawn or at least delayed. A few state regulators only requested delayed implimation of the rule until they next revised their State Implimentation Plans (SIPs) for Prevention of Significant Deteriouration (PSD). EarthJustice supported the rule but opposed the idea that the cost of measureing fine particles should be a consideration. On behalf of the Sierra Club, the Clean Air Task Force, EarthJustice commented "We support EPA’s proposal to get rid of the policy but reject the line of questioning as to the benefits and costs associated with ending a policy that is illegal." The EarthJustice-led coalition also opposed delaying implimentation "EPA must immediately end any use of the Surrogate Policy – either by “grandfathered” sources or sources in states with SIP‐approved PSD programs – and may not consider whether some flexibility or transition is warranted by policy considerations."

The final rule did eliminate the Surrate Policy, but allowed states to delay implimentation and enforcement until the next sceduled revision of their Implimentation Plans. I code this as the EarthJustice coalition getting most of what they requested, but not a complete loss for the regulated coalition.

For the EarthJustice coalition, the dependent variable, *coalitions success* is 1, *coalition size* is 3, *business coalition* is 0, *comment length* is 7/85, `r round(7/85, 2)`, and *log mass comments* is log(0), `r log(0)`.

For the EarthJustice coalition, the dependent variable, *coalitions success*, is -1, *coalition size* is 129, *business coalition* is 1, *comment length* is and *log mass comments*, $x_i$, is log(0), `r log(0)`.



# Pre-analysis




