---
title: "Why do agencies (sometimes) get so much mail"
subtitle: ""
author: "Devin Judge-Lord"
date: "September 19, 2018"
output:
  xaringan::moon_reader:
    lib_dir: libs
    mathjax: "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML"
    css: xaringan-themer.css
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

class: center, inverse, middle

## This slideshow was created using R Markdown


```{r setup, include = FALSE, cache = TRUE, echo = FALSE}
# chunks options:
# hide code and messages by default (warning, message)
# cache everything 
knitr::opts_chunk$set(eval = TRUE, 
                      warning = FALSE, message = FALSE,
                      cache = TRUE,
                      fig.retina = 2,
                      fig.align = "center", dpi = 100)
# Xaringan settings
library("xaringan")
library("xaringanthemer")
mono_light(base_color = "#002b36",
          link_color = "#2aa198",
          header_font_google = google_font("Vollkorn"), 
          text_font_google = google_font("PT Sans"), 
          code_font_google = google_font("Inconsolata"), 
          code_inline_background_color    = "#F5F5F5", 
          table_row_even_background_color = "white", 
          extra_css = 
            list(".remark-slide-number" = list("display" = "none"), 
                 ".remark-inline-code" = list("background" = "#F5F5F5", 
                                                #e7e8e2; /* darker */
                                              "border-radius" = "3px", 
                                              "padding" = "4px")))
```


---

Question
--


---

class: center, middle, inverse

## 


---

class: middle, center

```{r, eval = FALSE}
devtools::install_github("yihui/xaringan")
```

### Read the documentation

<https://slides.yihui.name/xaringan/>


---


