
## Introduction

<!--To address this gap, -->
I assess the relationship between the number of
public comments and the amount of change between draft and final policy
texts. Next, I assess the relationship between the number of people
mobilized by each campaign and whether the campaign achieved its policy
goals. Finally, I theorize and test four mechanisms by which public
input may affect bureaucratic policymaking. Each mechanism involves a
distinct type of information that pressure campaigns may relay to
policymakers: technical information, information about the likelihood of
political consequences, information about the preferences of elected
officials, or information about the preferences of the attentive public.
Because scholarship on bureaucratic policymaking has focused on the
power of technical information, where insider lobbying is most likely to
matter and where outside strategies are least likely to matter,
political scientists have largely overlooked mass mobilization as a
tactic.

I find evidence consistent with the observable implications of mass
comment campaigns influencing policymaking through \[non-null results\]
but no evidence that mass engagement affects rulemaking processes or
outcomes through \[null results\].

## Theory {#influence-theory}

### Incorporating political information into formal models of rulemaking {#formal}

Formally, political information requires several crucial amendments to
existing information-based models of rulemaking. In the most
sophisticated model of notice-and-comment rulemaking to date,
@Libgober2018 posits a utility function for agency $G$ as
$u_G(x_F) = \alpha_0 x_f^2 + \sum_{i=1}^N \alpha_i u_i (x_f)$ where
$x_f$ is the spatial location of the final policy, $u_i$ is the
preference of a member of the public or "potential commenter" $i$, and
$\alpha$ is a vector of \"allocational bias\"---i.e. how much the agency
cares about its own preferences $\alpha_0$ relative to accommodating the
preferences of others $\alpha_{i=1:N}$. Bureaucrats balance their own
idea of their mission against their desire to be responsive. In
Libgober's model, $\alpha$ is a fixed "taste" for responsiveness to each
member of society, so agency decisions simply depend on their answer to
the question "what do people want?" Including political information
requires two additional parameters related to a second question "why
would the agency care?"

First, like other lobbying strategies, going public may shift the
strategic environment, leading an agency to shift its allocation in
favor of some groups and away from others. Let this strategic shift be a
vector $\alpha_s$. Second, campaigns may directly persuade agencies to
adjust their allocational bias, for example by supporting claims about
the number of people the group represents or the intensity or legitimacy
of their policy demands. Let this direct shift be $\alpha_d$ and
immutable taste now be $\alpha_t$. Having decomposed an agency's
allocative bias into three parts (its fixed tastes, shifting strategic
environment, and potential to be convinced), the agency's utility
function is now
$u_G(x_F) =  (\alpha_{t0} + \alpha_{s0} + \alpha_{d0}) x_f^2 + \sum_{i=1}^N (\alpha_{ti} + \alpha_{si} + \alpha_{di}) u_i (x_f)$.
If, after the comment period, an agency's strategic environment is
unchanged and it remains unpersuaded about which segments of society
deserve favor, $\alpha_s$ and $\alpha_d$ are 0, and the model collapses
to the original information game based on fixed taste. This less
plausible when groups go public and expand the scope of conflict.

Incorperating political information allows us to begin formalizing
intuitions about mechanisms of influence. For example, @Libgober2018
asks "What proportion of commenting activity can be characterized as
informing regulators about public preferences versus attempting to
attract attention of other political principals?" (p. 29). Adding
political information to the model allows us to formalize this question:
Under what conditions does the decision to comment depend on an
organization's beliefs about $\alpha_t$ versus beliefs about $\alpha_s$?
Empirically, we may often be able to infer that the difference in
commenting can be attributed to group $i$'s beliefs about $\alpha_{si}$
if the behavior of political principals varies but other observed
parameter values are similar across rules at a given agency.

Rational-choice explanations of why organizations comment on proposed
rules build on an intuition that potential commenters will comment only
when the benefits exceed the costs of doing so. This intuition ought to
apply to other lobbying strategies such as mass mobilization as well.
Adding an additional lobbying strategy into the model described above is
straightforward. In Libgober's model, a potential commenter has negative
quadratic preferences centered on their ideal policy $p_i$ and
$u_i = -(x_f - p_i)^2$ where $x_f$ is the final policy chosen by the
agency. An organization will comment if the cost of doing so is less
than the difference between their utility when the agency selects a
policy having been informed about the organization's ideal point $p_i$
versus when the agency selects a policy having made a guess about the
organization's ideal point, $z_i$. If $c_i$ is organization $i$'s cost
of commenting, then $i$ will comment if it expects to be better off
providing information than abstaining
$E[u_i | p_i] > E[u_i | z_i] + c_i$. Similarly, an organization will go
public when it expects that the cost of running a mass mobilization
campaign to be less than the difference in utility when the agency
selects a policy having been informed about the intensity of broader
public preferences $p_{public}$ versus when the agency selects a policy
having made a guess about the intensity of the attentive public's
preferences, $z_{public}$. If $c_{campaign, i}$ is organization $i$'s
cost of running a mass mobilization campaign, then $i$ will launch a
campaign if
$E[u_i | p_{public}] > E[u_i | z_{public}] + c_{campaign, i}$. This
suggests that mass mobilization with the aim of influencing policy, i.e.
going public, should be more common when agencies are either poorly
informed or distant from public opinion and potentially influenced by
the types of political information created by mass engagement.

Additionally, an organization may comment or run a mass mobilization
campaign if it benefits in ways that are independent of policy outcomes.
Strategies such as \"going down fighting\" can be incorporated by adding
exogenous benefit parameters to the utility function of the potential
commenter/mobilizer. Let $v_i$ be the benefit of commenting independent
of its effect on the policy outcome, such as pleasing members or to
reserving the right to sue. Let $w_i$ be the benefit of running a mass
mobilization campaign independent of its effect on the outcome of the
policy at hand, such as fulfilling expectations of existing members or
recruiting new members. An organizations utility function would then be
$u_i = -(x - p_i)^2 + v_i + w_i$.

Adding these parameters also resolves a puzzling result of Libgober's
model. Empirically, rules that receive comments do not always change.
This result is impossible in a model where bureaucrats only have known
fixed tastes and potential commenters only seek changes in policy. For
policy seeking organizations to lobby but fail to influence policy
requires that they may either be wrong about an agency's allocative bias
or their ability to shift it. Incorporating political information allows
change and uncertainty in an agency's biases. The result of commenting
without rule change also becomes possible if commenters are allowed a
strategy of "going down fighting" and incentives to do so.