## Conclusion {#ej-conclusion}

This analysis presents a rare, systematic account of a social movement's impact on specific policy outcomes across institutions and over time. It illustrates the importance of ideas in policymaking and how social movements can affect the policy process---even technocratic processes like agency rulemaking, where most U.S. law is now made. 

When activists raise issue frames
like environmental justice, there is a higher probability that
policymakers engage in discourse that highlights the distributive effects of policy. However, baseline rates of addressing environmental justice in rulemaking are so low that, even when activists raise EJ concerns, most policy documents pay no explicit attention to EJ. This general lack of attention persists across agencies and across the G.W. Bush, Obama, and Trump administrations. Indeed, I find surprisingly small differences across administrations in both baseline rates of considering EJ and responsiveness to public pressure. 
In contrast, there is a great deal of variation across agencies, suggesting that policy receptivity and responsiveness to public input are conditional on slow-moving
institutional factors such as organizational cultures and institutional mechanisms for processing political information. Some agencies are more receptive to claims about distributive justice than others.

Bureaucracies are specialized institutions built to make and implement certain kinds of policies based on certain goals and types of legitimate knowledge. Each agency has distinct norms and biases. Some may see an issue as "environmental" when others do not. Likewise, some may see disparate impacts that demand consideration as issues of fairness and distributive "justice" where other officials, with different norms and training, see no such disparity. In short, some policymakers appear to see their policy area as more related to environmental justice than others and thus be more receptive to commenters' concerns. 

The policy outcomes suggested by an environmental justice analysis depend on how the populations of concern are defined. In some cases, those raising environmental justice concerns present it as an economic inequality issue, leading policy to account for disparate impacts on low-income populations. In other cases, groups raise claims rooted in cultural practices, such as fish consumption among certain tribes. As occurred in the Mercury Rule, the analysis in subsequent drafts of the policy used evaluative criteria specific to these communities. Thus, policy outcomes depend on the specific environmental justice concerns raised. Future research should assess the relationship between distinct types of EJ claims and corresponding policy changes. <!--TODO REVIEW HAND-CODED RESULTS--> 

Which communities and concerns are raised by pressure campaigns depend on second-order representation---who makes decisions in the organizations that mobilize public pressure. Examining which groups raise environmental justice concerns and second-order participation in these organizations' advocacy decisions validates some of the skepticism about who is able to participate and make their voice heard. Elite groups dominate policy lobbying, even on an issue like environmental justice. National advocacy organizations frequently request that regulators protect "all people" or even "low-income communities of color." However, this more generic advocacy may not lead to the same outcomes as participation by groups that can present more specific local environmental justice concerns unique to a community. 

Several types of organizations raise environmental justice concerns. Some are generic progressive advocacy organizations. Others are community-based organizations. Linking these two types are high-capacity national organizations that frequently partner with local organizations for place-based litigation and campaigns. National advocacy groups that partner with frontline community groups may be more likely to raise local concerns in national policymaking than groups that focus almost exclusively on national campaigns. Given the importance of federal policy for local environmental outcomes, and advocacy organizations' potential to draw policymakers' attention to environmental justice issues, future research should examine the quality of partnerships between frontline communities and national advocacy organizations.

The quality of representation is more than an academic concern. Policymakers must make sense of representational claims in order to understand the political environment in which they act. Political information like petition signatures thus has the power to affect policy. While lobbying disclosure requirements could be amended to provide other information about how well groups represent the constituencies they claim to represent [@Seifter2016UCLA], letter-writing campaigns are one of the only strategies currently available to demonstrate issue-specific congruence between the positions of groups and the people they claim to represent (see Chapter \@ref(whymail)).

The above analysis focuses on one particular type of political action that is likely correlated with other forms of activism, lobbying, and civic engagement. For example, future research could explore connections between pressure campaigns and protests, both for organizers and participants. Likewise, future research could measure media attention to agency rules and the various issue frames that media coverage promotes. It is difficult to disentangle the effects of co-occurring inside and outside lobbying strategies. However, future research could look at other tactics pathways for activists to raise distributive justice concerns and affect policy. For example, campaign leaders often meet with policymakers, commission scientific reports, and encourage letter-writing to politicians.

Future work could also explore connections between geography, identity, and participation in campaigns. To date, environmental justice scholarship has focused on geography-based inequalities. These inequalities and harms may have cross-cutting effects on civic participation. On the one hand, exposure to environmental harms may inspire civic engagement, especially around distributive justice frames like environmental justice [@Taylor2002]. On the other hand, economic and environmental inequality create inequalities in the time and resources for civic participation [@Piven1977; @Soss2007; @Michener2018]. The receptivity of government institutions to different identities [@Harrison2019] may also affect the tactics activists use [@Taylor2002].

In the end, the above analysis offers some clarity on two poorly
understood and rarely linked features of U.S. politics: the policy impact of social movements and the role of public pressure in bureaucratic policymaking. It offers
some hope that policymakers may at least acknowledge concerns raised through direct democracy mechanisms like public comment periods. At the same time, it highlights how policymakers rarely explicitly address the disparate impacts of policy, even when directly confronted with distributive justice concerns.   Social movements do affect the policy process in aggregate terms, but there are steep odds to overcome in any given policy fight.