### Tracing Ideas Through Rulemaking: Environmental Justice as a Contested Concept {#ej-methods}

Using an environmental justice frame does not always imply the same communities of concern. Environmental justice emerged from movements against environmental racism, especially the disposal of toxic materials in predominantly Black neighborhoods [@Bullard1993]. However, the term quickly took on other meanings, encompassing various marginalized groups. President Clinton's 1994 Executive Order on Environmental Justice required all parts of the federal government to make "addressing disproportionately high and adverse human health or environmental effects of programs, policies, and activities on minority populations and low-income populations" a core aspect of their mission. This meant considering the disproportionate effects of policies by race and income during rulemaking, thus broadening the scope beyond race.

In 2005, EPA political appointees reinterpreted the Order, removing race as a factor in identifying and prioritizing populations. This move was criticized by activists and two reports by EPA's own Office of Inspector General ([EPA-OIG-2004-P-00007](https://www.epa.gov/sites/default/files/2015-12/documents/20040301-2004-p-00007.pdf) and [EPA-OIG-2006-P-00034](https://www.epa.gov/sites/default/files/2015-11/documents/20060918-2006-p-00034.pdf)). 

President Obama's EPA Administrators reestablished race as a factor. They named EJ as one of their top priorities, but they also faced criticism from activists for paying lip service to environmental racism without adequate policy changes.

In an October 2017 proposed rule to repeal
restrictions on power plant pollution, the Trump EPA acknowledged that "low-income and minority communities located in proximity to [power plants] may have experienced an improvement in air quality as a result of the emissions reductions." This is remarkable given that "assertions that hazardous facilities are concentrated in minority and low-income communities in the United States and that those communities are exposed to inordinate amounts of environmental hazards" are "the most controversial claims of the environmental justice movement" (@Taylor2014, p. 1). Because the Obama EPA discussed EJ when promulgating the Clean Power Plan rule (stating that "climate change is an environmental justice issue"), the Trump EPA attempted to reframe rather than ignore environmental justice. The Trump EPA contended that the Obama EPA "did not address lower household energy bills for low-income households [and that] workers losing jobs in regions or occupations with weak labor markets would have been most vulnerable" (EPA 2017). Like regulated industry commenters, these statements frame the distribution of jobs and electricity costs as EJ issues in order to push back against policies that would equalize the distribution of health impacts from pollution. 

The central conflict over the role of race in policy analyses is just one of many conflicts that the environmental justice movement has caused to be fought somewhat on its terms. The next section briefly reviews the decades-long policy fight over regulating mercury pollution to illustrate how these definitional conflicts shape rules and rulemaking. This case and other examples in this article emerged from reading hundreds of rulemaking documents where agencies did and did not respond to comments raising EJ concerns. Their purpose is to assess whether the cases in the quantitative analysis are plausibly what they appear to be: that changes in rule text are, sometimes, causally related to public comments and that non-changes are cases of agencies disregarding comments, not some accident of the data or measures. 
The qualitative reading also confirmed other key assumptions, such as the fact that advocates do, in fact, use "environmental justice" when they raise distributional concerns, even on many rules that are not about issues traditionally considered "environmental."


#### The Evolving Distributive Politics of Mercury Pollution

Definitions of the public good and minority rights are
implicit in most policy documents, including agency rules. The public comment process offers an
opportunity to protest these definitions. Protest is one way that
marginalized groups can communicate opinions on issues to government
officials [@Gillion2013]. In the EPA's Mercury Rules, two
definitional issues were decisive. First, as with many forms of pollution,
mercury-emitting power plants are concentrated in low-income and
non-White communities. Second, some populations consume much more
locally-caught freshwater fish, a major vector of mercury toxicity.
Studies inspired by the political controversy around the Mercury Rules
found high risk among certain communities, including "Hispanic, Vietnamese, and
Laotian populations in California and Great Lakes tribal populations
(Chippewa and Ojibwe) active on ceded territories around the Great
Lakes" (EPA 2012). Thus the standards that EPA chooses depend on whom the regulation aims to protect: the average citizen,
local residents, or fishing communities. Mercury regulations have disparate
effects based on race and class because of disparate effects based on
geography and cultural practices. 

In December 2000, when the EPA first announced its intention to regulate
mercury from power plants, the notice published in the *Federal Register*
did not address EJ issues, such as the disparate
effects of mercury on certain populations; it only discussed anticipated impacts in
reference to "the U.S. population" (EPA 2000). When the first draft rule
was published, it only discussed the effects of the rule on regulated
entities, noting that "Other types of entities not listed could also be
affected" (EPA 2002). 
Commenting on this draft, Heather McCausland of
the Alaska Community Action on Toxics (ACAT) wrote:

> The amount of methyl-mercury and other bioaccumulative chemicals consumed by Alaskans (especially Alaskan Natives) could potentially be much higher than is assumed... [This could increase] the Alaskan Native mortality rate for babies, which according to the CDC, is 70% higher than the United States average. Indigenous Arctic & Alaskan Native populations are some of the most polluted populations in the world. <!--Global transport & old military sites contaminate us too. ([EPA-HQ-OAR-2012-0452-0006](https://www.regulations.gov/comment/EPA-HQ-OAR-2012-0452-0006))-->

By citing the CDC, McCausland's comment provided both technical and distributive information. As allies mobilized, public pressure mounted to address the disparate impacts of mercury levels.
After receiving hundreds of thousands of comments and pressure from
tribal governments and organizations, a revised proposed rule echoed McCausland's
comment noting that 

> Some subpopulations in the U.S., such as Native
Americans, Southeast Asian Americans, and lower-income subsistence
fishers may rely on fish as a primary source of nutrition and/or for
cultural practices. Therefore, they consume larger amounts of fish than
the general population and may be at a greater risk of the adverse
health effects from Hg due to increased exposure ([04-1539/p-719](https://www.federalregister.gov/d/04-1539/p-719)).

After nearly a million additional public comments, a further revised proposed
rule ultimately included five pages of analysis of the disparate impacts
on "vulnerable populations" including "African Americans," "Hispanic,"
"Native American," and "Other and Multi-racial" groups (EPA 2011). In the final rule, "vulnerable populations" was replaced
with "minority, low income, and indigenous populations" (EPA 2012). The EPA
had also conducted an analysis of sub-populations with particularly high
potential risks of exposure due to high rates of fish consumption as well
as additional analysis of the distribution of mortality risk by
race.

Of this second round of comments, over 200 unique comments explicitly raised
EJ issues. The Little River Band of Ottawa Indians
expressed the Tribe's 

> ...frustration at trying to impress upon the EPA the multiple and profound impacts of mercury contamination from a Tribal perspective. Not to mention the obligations under treaties to participate with tribes on a 'Government to Government' basis. At present, no such meetings have occurred in any meaningful manner with EPA Region V, the EPA National American Indian Environmental Office, nor the State of Michigan's Department of Environmental Quality... In this rulemaking, the EPA perpetuated, rather than ameliorated, a long history of cultural discrimination against tribes and their members ([EPA-HQ-OAR-2009-0234-12462](https://www.regulations.gov/comment/EPA-HQ-OAR-2009-0234-12462), p. 67). <!-- (Sprague
2011). -->

<!-- See Dwidar --> 

Did comments like these play a role in EPA's changed analysis of whom mercury limits should aim to protect? Because of the many potential sources of influence, it may be difficult to attribute causal effects of particular comments on a given policy.
However, comments may serve as a good proxy for the general mobilization
of groups and individuals around an administrative process, and it is
not clear why else the EPA would not address EJ in the first
draft of a rule and then add it to subsequent drafts in the absence of
activist pressure. Electoral politics does not offer an easy
explanation. The notice proposing the Mercury Rule was issued by the
Clinton administration, the same administration that issued the
Executive Order on Environmental Justice, and the subsequent drafts that
did address EJ issues were published by the Bush
administration, which had a more contentious relationship with
EJ advocates, while Republicans controlled both
houses of Congress. The expansion of the analysis from one draft to the
next seems to be in response to activist pressure.
