## Introduction {#macro-intro}

Do the issues that dominate political discourse translate into real policy? To the extent that broad theories of American politics go beyond the results of elections and attempt to explain the resulting policies, they generally focus on landmark legislation and items at the top of presidential agendas. Yet as the administrative state and our understanding of it has grown, political scientists are increasingly paying attention to policy outputs both for their own sake and for the ways policy outputs shape politics. Administrative rules and regulations are where the rubber hits the road for both legislation and presidential agendas. Ninety-percent of U.S. law is now written by agencies rather than Congress (West and Raso 2013) and the real impact of most new statues and executive orders is largely unknown until the ink is dry on the agency rules and regulations that implement them.

Legally binding regulations give specific meaning and force to legislation and presidential agendas. If changes in the public mood and the priorities of elected leaders matter for policy, we would expect to see these changes borne out in the number and type of regulations published. Regulations are the substantive outputs of policy processes. Changes in outputs may reflect changes in the substantive inputs—the issue structure—or changes in how issues are filtered and activated by the institutional structures of policymaking. 

This chapter martials data on federal agency policymaking between from 1980 to 2020 to sketch broad trends in federal policymaking. Broad theories of American suggests three types of predictions: patterns in (1) the substantive issues addressed by policy, (2) the relationship between partisan control and issue attention, and (3) the pace of policy change.


### Patterns in Policy Issues

Following Mayhew (1991, 2008), Claggett and Shafer (2010) argue that the policy issues driving American politics vary over time. They distinguishing four broad categories of political issues: welfare, international relations, civil rights, and cultural issues. These categories are constructed to have policy relevant content, but still are somewhat different from the way the bureaucracy is organized and thus our ability to categorize regulations. Nevertheless, their findings regarding issue structure of American politics have observable implications for the quantity and substance of federal rulemaking. 

They find that National Security was a major issue in 1984, but then faded in 1988 until it emerged as the dominant issue of the 2004 election. Welfare was also a top issue in 1984 but continued to be salient and the dominant issue in several elections. Opinions on Foreign Engagement reversed the direction of correlation with presidential vote, suggesting that the first Bush and Clinton administrations may be more similar in their attention to foreign policy than the second Bush administration. Claggett and Shafer found civil rights to be in mildly salient in 1988, 1992, and 2000 but not elsewhere. They find cultural issues, operationalized through a dimension called Behavioral Norms to be highly salient from 1992 to 2000. Unfortunately, what Claggett and Shafer call behavioral norms is either so distant from policy (e.g. women’s’ roles) or so fragmented across agencies (e.g. school prayer and abortion) that it is not possible to make predictions the location of policymaking from patterns on this issue.

The finding that social welfare is a major feature of American politics (Sundquist 1968, Claggett and Shafer 2010) should be reflected in agency policymaking. 

In sum, if the issue structure of politics shapes policy, past scholarship suggests that social welfare should be the leading type of policy over all periods and for both parties. Social welfare is identified as a dominant dimension of party alignment and of issue structure in public opinion. 

### Party Control and Policy Issues

The role that parties play in the making of regulations is unclear. The greatest effect parties may have is through presidential platforms and agendas, but partisan control of Congress also matters, especially when Congress is making policy or when agencies fear that a hostile Congress will override their policies (Potter Forthcoming). We may think of agency policymaking as consistently affected by presidential agenda with Congress providing shocks and constraints.

With respect to the anticipated attention paid to different policy areas, scholarly perspectives on American politics that focus on substance can be lumped into two types: (1) those that generally predict that both parties pay attention to the same issues at the same time (theories of partisan alignment (e.g. Sundquist) and (2) those that generally predict that parties pay attention to different issues (including both theories of party ideologies (e.g. Gerring 1998) and theories of party coalitions (e.g. Schlozman 2015). In each case, the particular issues may vary more or less dramatically depending on how sharply one defines historical periods (compare the issue evolution perspectives [Carmines and Stimson 1989] with critical elections perspectives [Key 1993]). Indeed as Shafer (2016) notes, some periods may end quickly and others slowly. Given the limited time period of this paper, I focus on the dominant policy issues, their relationship to party control, and the pace of policymaking rather than the timing or pace of transition between periods. 

These two types of theories generate broadly contrasting predictions about what we expect government to do under levels of party control. For alignment theories, we would expect to see agency policymaking dominated by the major issues of the day under both parties. Parties may have opposite positions on these issues leading the agencies to be pulled in opposite directions by political leaders, but the relevant set of agencies will remain largely the same. Occasionally, an agency with somewhat overlapping authority may be mobilized, but the policy area will be the same. Under theories of party ideologies and party coalitions, party control should determine which issues are attended to and thus have a much larger effect on which agencies are making more policy.^[This may occur through positive agenda control that the president has to direct agency policymaking or negative agenda control the president has through the Office of Information and Regulatory Affairs review [@Potter2016]. Negative agenda control is likely to dominate in Congress (Cox and McCubbins, 2005), but the threat of Congressional action may be sufficient to influence agency policymaking [@Potter2016]. ]

The first type necessarily identifies dominant issue dimensions where each party is doing the opposite of the other. In Sundquist’s model re-alignment can occur slowly or rapidly whereas Manza and Brooks emphasize how social structures, and thus issues, change slowly. Almost all prominent alignment theories, however, identify 1980 through the present as one period (indeed, most see 1936 as the critical election that has oriented the modern era). Thus instead of engaging realignment theories on the issue of realignment, I draw on them for the issues they claim constitute the dimension of the current alignment. By these theories, the dimensions of substantive conflict and thus the distribution of agency policymaking should be relatively stable over the period considered in this paper. 

Realignment theories suggest that certain policy areas consistently dominate all others and, while the direction of policy will likely change, the issues will vary little with changes partisan control. Presidential transitions may be marked by withdrawal or reversal of policies made under the previous administration and congress may overturn agency rules but the relevant agencies will be the same, generally those dealing with social welfare.  

The second type focuses on the differences of party ideologies, and its predictions are less clear. Gerring identifies distinct and consistent ideologies in both parties. Rather than a dominant dimension of conflict where parties are responding to each other (as in alignment theories) or an underlying dimension of issue structure (e.g. Claggett and Shafer 2010), for Gerring, party ideologies are the policy agendas of party elites. “Party constituencies were generally conservative forces, whereas party elites were the agents of change” (Gerring 1998, pg. 272). 

In the current era, Republicans are driven by Neoliberalism and Democrats by Universalism. Like others, Gerring sees social values (behavioral norms) playing a prominent role in Republican policy agendas from 1980 to when the book was published in 1996 (see pg. 277). Yet, he argues, the core of the platform was neo-liberal opposition to the welfare state and promotion of free markets. In contrast, Gerring identifies the Democratic platform in this period as consistently emphasizing broad unifying issues like Medicare and education. While this more clearly suggests the policy areas likely to receive attention under Democrats than Republicans, it does generally imply that the policy agendas will be different, not simply opposite. 

Under theories emphasizing party ideologies and interests, the volume of policymaking at different agencies may very well change substantially when a different party captures the presidency. Specifically, if Gerring (1998) correctly identified the party ideologies of the current era, we would expect significantly more civil rights and welfare policymaking under Democratic administrations and more neoliberal economic policy under Republican administrations, especially when presidents’ copartisans have majorities in Congress. Gerring’s distinction between Democrats statism and Republicans anti-statism may also suggest more rulemaking overall in Democrat administrations. 

Perspectives focusing on interest groups and coalitions also suggest that issues will vary with party control. If parties contain coalitions of intense policy demanders (see Cohen. Noel, Karol, and Zaller 2008 and Disalvo 2012), the issues to which they attend will reflect these different coalitions. Disalvo shares Gerring’s conclusion regarding the anti-statism of the Republican party. Most clearly, Schlozman (2015) links Democratic politics and labor groups. While Schlozman emphasizes that labor groups frequently fall short of their goals within the Democratic coalition, no other group is a stronger anchor. We thus expect much more labor policy under Democratic administrations. As the interest groups Schlozman identifies anchoring Republican party are focused on behavioral norms where policymaking is less concentrated in certain agencies, these predictions are less relevant. Again these copartisans in Congress ought to increase these effects.

All of the above perspectives emphasize party difference, either on ideology (on the same issues for Sundquist, on different issues for Gerring) or anchoring interests. In contrast, Samuel Huntington in The American Creed and Gary Hart emphasize commonality. Whereas Gerring finds “broad symbols that both parties appropriate—liberty, freedom, democracy, equal opportunity, and so forth, often mean fundamentally different things to spokespersons of different parties” (Gerring 1998, pg. 8), Huntington sees these as a core American ideology exerting an independent force on politics. 

### Policymaking and Policy Outcomes On Different Issues 

*The American Political Pattern: Party Balance, Ideological Polarization, and Substantive Conflict, 1932-2016* (Shafer 2016) offers one account that integrates both issue structure and party control. Patterns of substance of conflict and balance of party control produce patterns of policymaking. Most clearly, Shafer observes a pattern of consistent major policymaking in the years between 1980 and 1992 and a pattern of punctuated equilibrium after 1992. Such patterns of policymaking should be visible in patterns of rulemaking. 

This book is also a prominent exception to the common view that 1980-2016 falls within one period. He identifies 1969-1992 as the Era of Divided Government and 1992 through the present as the Era of Partisan Volatility. Importantly, *The American Political Pattern* discusses not only landmark policies and agendas but also identifies distinct patterns of policymaking. The Era of Divided Government is associated with a steady flow of major policies especially regarding the economy and the environment. In contrast, the Era of Partisan Volatility is characterized by periods of policy stability and punctuation. One aim of this paper is to assess the extent to which patterns of administrative policymaking fit these patterns. 

Shafer is clear that his periods are characterized by their policy process not policy outputs. Nevertheless, given a certain intersection of dominant issues and type of policy process, we should expect to see a pattern of policy outputs. The era of divided government is dominated by social welfare and cultural values and cross-partisan coalitions suggesting that the volume of policy outputs should be concentrated on social policy and civil rights be fairly consistent across configurations of party control. 

If the Era of Partisan Volatility is characterized by a long stretches of policy stasis punctuated by spikes of activity, we should see a pattern of lulls and spikes in rulemaking. Furthermore, we have reasons to suspect that party control may lead to different types of policymaking, but if issues have indeed collapsed we should see issues moving together over periods of partisan control. The observation of punctuated equilibrium in legislative policymaking could also suggest a pattern where, in the absence of new legislation, the president may have a larger effect over patterns of administrative policymaking. 

Scholarship thus gives us predictions regarding the issues that dominate American politics and how party control will affect the translation of issues into policy. This two-fold space for disagreement raises a problem for the focus on policy outputs in the present analysis. If we do not see policymaking on an issue, it could be evidence that the issue was not as important as claimed or that the party in power deemphasized it. Only by assuming a certain issue structure or a certain theory of party effects could we say that an absence of policymaking supports one perspective or another regarding issues or institutional structure. The evidence is sufficient, however, to rule out some explanations. The remainder of the paper focuses on consistencies and inconstancies between the evidence and theories with no claim that consistency means the theory is correct. 

## Methods and Data 

This exercise compares research on the social structure and political behavior of American public and political elites with what government actually does. The subject of administrative policymaking is driven in part by laws passed by Congress and in part by the agenda of the President. Discrepancies may indicate either a true disconnect between electoral politics and executive action or that executive policymaking was constrained by other political forces. 

Connecting broad theories of the American political landscape to the nuanced daily actions of government is not easy. I focus on relatively fine-grain policy outputs, final rules published by agencies in the Federal Register and reported to the Office of Information and Regulatory Affairs. This approach has the advantage of capturing the making of law as it really is, not how it is framed by elites or thought of by the electorate. The disadvantage is its distance from policy inputs. While social cleavages along class, religion, or race can be connected to voting patterns, it is much more difficult to say how they affect the lawyers sitting at desks in the federal bureaucracy writing the minutiae of the law. 

My data source is the Unified Agenda of Regulatory and Deregulatory Actions. These data reflect the magnitude of different types of policymaking but not the direction. As the name suggests, many rules may be reversing a previous rule. However, it does indicate that attention and resources are being devoted to the policy area and thus that it is a salient issue for administrative policymakers. Whether these issues align with issues salient to mass public and political elites is the subject of the present investigation. 

These data were compiled from two sources published by the White House Office of Information and Regulatory Affairs. Since the Reagan administration, agencies have been required to report their rulemaking activities for semi-annual publication in the Unified Agenda of Regulatory and Deregulatory Actions. Separately, ORIA issues annual reports from the Office of Management and Budget (OMB) regarding the rules it has reviewed. OMB only reviews significant rulemakings (generally those with significant economic impact or affecting other areas of government), but their data helps correct reporting errors and gaps in the Unified Agenda, ensuring that at least significant rules are included and correctly dated. Together these sources yield a dataset of 56,304 unique rulemaking projects as identified by a Regulation Identification Number (RIN). RINs allow us to track a rule from the publication of a draft to the eventual publication of a final rule (or withdrawal). 

Regulation Identification Numbers are allocated by agency, allowing me to disaggregate the OIRA reports by policy area. I generally followed the policy areas identified by the Policy Agendas Project (Baumgartner et al., 2016). The first two numbers of a RIN generally signify the department and the next two, the bureau within the department. Many issue areas, like welfare and foreign affairs, cross multiple entire departments while others, like civil rights, are the domain of only a few sub-bureaus. 

I visually present rulemaking activity over time in three different ways. The simplest visualization is a histogram like the one below. In these plots, blue lines mark transitions to a new Republican president and red lines mark transitions to a new Democratic president. The other two methods of visualizing 

[all rules histogram] 


### Scatterplots of Rulemaking

In addition to histograms of the number of rules, we can see patterns in rulemaking by plotting the date a rule is finalized or withdrawn on a scatterplot. On the y-axis is the Regulation Identification Number. This type of number is assigned in temporal order within each bureau or sub-agency. For example, the lower half of the plot below shows a high and steady rate of rulemaking by the Centers for Medicare and Medicaid and the upper half shows a very modest rate of rulemaking at the Social Security Administration prior to the passage of the 2003 Medicare Modernization Act, which gave it a more prominent role in administering Medicare.

Other major political events can be seen in the scatterplots. For example, the gap in rulemaking activity between 1995-1996 reflects the government shutdown. We also see the abrupt end of agencies and departments including those in the Department of Justice and Department of Transportation, reflecting their reorganization into the Department of Homeland Security after the attacks of September 11, 2001. This included the Coast Guard and Transportation Security Administration from the Department of Transportation and several agencies including the Immigration and Naturalization Service from the Department of Justice (see scatterplots in the Appendix). 

There is a stark increase in the number of rules being withdrawn across policy areas beginning with the election of George W. Bush and continuing into the Obama administration. Withdrawals may indicate that the draft regulations started by the previous administration are being canceled, that new legislation is passed, or, more likely, that there is simply a more systematic practice of reporting withdrawals. 

In any of these figures, one can observe the general rate of rulemaking in each bureau as the slope of the line of black squares. Points below the line are rules that took longer than usual to finalize. Thus, these figures allow us to see the relative rate of rule finalization and withdrawal as well as the variance in how long rules take to make. 

### THe Likelihood of Rulemaking over Time

Finally, we can estimate statistical trend lines for different policy types. While many statistical approaches may be appropriate, I opt to use a proportional hazard model. This method estimates a baseline hazard rate–the likelihood a rule will be published given the number of days since a draft was released. I then estimate the effect of calendar time on this baseline hazard rate. The effect of calendar time on the likelihood of rule finalization is fit using a smoothing spline for every two years (every Congress, in this case 18) in the dataset. These splines estimate a cubic polynomial function that best captures the effect of a given date on the likelihood of rulemaking over the spline interval while also smoothly connecting to the intervals on either side. This gives us a smoothed function estimating the likelihood of rulemaking over time (see figures for social and economic policy in the next section). 

By including the date the draft rule was published, this approach captures two things not well-captured by histograms and scatterplots. It accounts for the pace of rulemaking, i.e. the time it takes from draft to completion, and the likelihood that long-delayed rules will be finalized. Both of these indicate that the issue is politically salient. 

Two notes are important for interpreting these figures. First, in 1994, President Clinton issued an executive order that only significant rules were to be subject to ORIA review. Unfortunately, this coincides with the dramatic 1994 election that broke Democratic control of Congress, so inferences about this time are limited. It may be safest to assume the universal dip in the likelihood of policymaking around 1994 is an artifact of this executive order and thus to imagine trend lines shifted up to have a mean of the value at 1994. Second, this method is sensitive to outliers at the ends of the distribution. We should be especially cautious making inferences from the first years that agencies were required to report these data as they may have been inconsistent. Thus, it is safest to look at the period between 1985 and 2015. 

## Policy Substance in Regulations

This section presents selected figures and brief commentary on the extent to which patterns observed in rulemaking fit or conflict with those observed elsewhere in the political system. 

### Social Policy, Economic Policy, and Foreign Policy

I start with the broadest categorizations of social policy and economic policy. 
Social policy does not mean social issues as described by Shafer and Spady (2014) or Carmines, Ensley, and Wagner (2012). Social policy is also broader than welfare. It includes not only Medicare, Medicaid, Social Security, and food and housing assistance, but also public education, labor, and civil rights. It is a combination of the departments of Education, Health and Human Services, Labor, Veterans Affairs, and Justice, as well as the Social Security Administration, Centers for Medicare and Medicaid, and a variety of other departments dealing with health, poverty, and civil rights. 
Economic policy includes the Departments of Commerce, Treasury, Energy, Transportation, Agriculture, and Interior. 

The likelihood plots below are not clear evidence for or against theories that suggest Democrats and Republicans should differ in their emphasis on these two broad categories. On the one hand, the patterns are not noticeably different before the 2000 election, and both George W. Bush and Barack Obama appear to have made more economic policy in their first term than in their second. On the other hand, there is a marked increase in the likelihood of social policy under the Obama administration as suggested by the party ideology perspective put forward by Gerring (1998) and others. Social policy will be disaggregated to more specifically consider welfare, labor, and civil rights policymaking in the subsections below, but first, I turn to a third broad category of policymaking, foreign policy. 

The histogram for foreign affairs (the Department of State and International Trade Administration) does look different than the Department of Defense, but the only clear pattern is the increased rulemaking after 1996, predating the dramatic increase in its budget after 2001 and significantly predating the 2004 election when Claggett and Shafer (2010) identify national security as emerging as an issue. 
The likelihood plot suggests partisan effects with two peaks occurring during the 103rd and 111th Congresses, the only periods where Democrats had control of both houses and the presidency. This aligns with Farhang and Yaver’s (2015) finding that rulemaking is more likely to be concentrated in a single agency rather than fragmented across agencies under unified government. There are smaller bumps that appear to correspond to the reelection of these two presidents when facing an oppositional Congress (but also no longer thinking about reelection). 


### Labor and Welfare 

Schlozman’s story about the connection between labor and the Democratic party is not seen in Depart- ment of Labor regulations. If anything, Republican administrations seem to see more labor policymaking. Looking at the scatterplot, policymaking appears remarkably constant across sub-agencies within the De- partment of Labor, barring a marked pulse of rule withdrawals in 2001. 
   
Clear peaks in welfare rulemaking (Social Security, Medicare, and Medicaid) reflect the 2003 Medicare Modernization Act and the 2010 Affordable Care Act. The histogram suggests that policymaking both increased and became more variable after 2000. This pattern is most consistent with Shafer’s character- ization of the Era of Partisan Volatility. We do not see clear patterns associations with party balance, but this may be because we are looking at the amount of policy rather than its direction. The scatterplot shows significant numbers of rules withdrawn after 2001, which may indicate partisan disagreement.
   


### Civil Rights

Among others, Mayhew (1991) and Claggett and Shafer (2010) identify civil rights as one of the major new issues on the post-war American policy agenda. Unfortunately, the making of regulations is likely a poor measure of this issue, and classifying regulations only makes this problem worse. Only a few sub-agencies unambiguously address only civil rights issues. The figures below reflect the Department of Agriculture Office of Civil Rights, The Department of Housing and Urban Development’s Fair Housing and Equal Opportunity bureau, and the Equal Employment Opportunity Commission, none of which make many regulations. Little can be said about so little data, but rulemaking activity does appear to peak near the beginning of the Clinton administration and remain nearly non-existent since the beginning of the George W. Bush administration. Future research could search for additional activity using keywords in rule abstracts. Yet it is possible that civil rights, described by Claggett and Shafer (2010) as anti- discrimination policy (especially in criminal justice) and race consciousness are meaningful for structuring votes, but are little reflected in federal regulations. In contrast, civil rights politics may have large impact on local policy and courts. 

[CIVIL RIGHTS SCATTERPLOT AND HISTOGRAM]

### Environment

The cleanest way to capture environmental issues is to focus only on the Environmental Protection Agency and that is what the figures below do. However, environmental issues are also spread throughout the Departments of Agriculture, Energy, Defense, and, increasingly, State. 
Claggett and Shafer (2010), among others, identify environmental issues as anomalous or off-dimension issues that may not cluster well with other issues. Shafer 2016 identifies environmental issues as a major policy issue in the Era of Divided Government. The rulemaking data, especially the histogram, do not contradict these interpretations. Unlike any other policy areas, the peak of environmental regulations in this timeframe is when Reagan takes office (probably capturing the end of the era of new landmark environmental legislation) and decline dramatically by the end of his term to a level that will remain for the next three decades.
   
The likelihood plot does show peaks in the 103rd and 111th Congresses, suggesting partisan effects. However, this partisan association could be as much an artifact of the agency as the issue. For example, Republicans may be inclined to pursue environmental protection through the Departments of Agriculture, Energy, or Defense in which they may have more trust or better policy vehicles to serve their constituents (see Appendix for additional plots). Alternatively, policymaking in the EPA may be indicative of policy- making in other venues where Democrats may also pay more attention to environmental issues. Future research could analyze the abstracts of rules in more multi-issue agencies to better determine their content. The most pronounced peak may reflect Barack Obama’s executive actions in his second term (for example his executive order on climate change adaptation (Obama 2013)). 

## Refrences

Baumgartner, Frank R., Bryan D. Jones, John Wilkerson and E. Scott Adler. 2016. “Policy Agendas Project.” Online database distributed by the Department of Government at the University of Texas at Austin, http://www.comparativeagendas.net/. 

Carmines, Edward G., Michael J. Ensley, and Michael W. Wagner. 2012. “Political Ideology in American Politics: One, Two, or None?” The Forum, 10 (4): 1-18. 

Carmines and Stimson. 1989. Issue Evolution: Race and the Transformation of American Politics. Princeton University Press. 

Carpenter, Dan, and David Moss. (Eds.). 2013. Preventing regulatory capture. Cambridge University Press. 
Claggett, William J.M. and Byron E. Shafer, The American Public Mind: The Issue Structure of Mass Politics in the Postwar United States. New York: Cambridge University Press. 


Cox, Gary C. and Mathew D. McCubbins. 2005. Setting the Agenda: Responsible Party Government in the U.S. House of Representatives. New York: Cambridge University Press. 

Farhang, Sean. and Miranda Yaver. 2015. “Divided Government and the Fragmentation of American Law” American Journal of Political Science. 108(7): 2643-2650 

Gerring, John. 1998. Party Ideologies in America, 1828-1996 New York: Cambridge University Press. Huntington, Samuel P. 1981. American Politics: The Promise of Disharmony Cambridge, MA: Harvard 
University Press.

Kerwin, Cornelius, and Scott R. Furlong. 2011. Rulemaking: How government agencies write law and 
make policy. 4th ed. Washington, DC: Congressional Quarterly.

Key, V.O. 1993. A Theory of Critical Elections. Ivington Publishers.

Lewis, David E. 2008. The Politics of Presidential Appointments: Political Control and Bureaucratic 
Performance. Princeton, NJ: Princeton University Press.

Manza, Jeff and Clem Brooks. 1999. Social Cleavages and Political Change: Voter Alignments and U.S. 
Party Coalitions. Oxford: Oxford University Press.

Mayhew, David R. 1991. Divided We Govern: Party Control, Lawmaking, and Investigations, 1946-1990. 
New Haven: Yale University Press.

Obama, Barack. 2013. “Executive Order – Preparing the United States for the Impacts of Climate 
Change”

Potter, Rachel. Forthcoming. Journal of Politics.

Schlozman, Daniel. 2012. When Movements Anchor Parties. 2015. Princeton University Press.

Shafer, Byron E. 2016. The American Political Pattern. University Press of Kansas.

Shafer, Byron E. and Richard H. Spady. 2014. The American Political Landscape. Cambridge, MA: 
Harvard University Press.

Sundquist, James L. 1983. Dynamics of the Party System: Alignment and Realignment of Political 
Parties in the United States. Washington, DC: Brookings Institution.

West, William F., and Connor Raso. 2013. “Who Shapes the Rulemaking Agenda?.” Journal of Public 
Administration Research and Theory 23(3): 495519.
Wilson, James Q. 1967. “The Bureaucracy Problem.” The Public Interest: 3. 


