## Introduction {#why-intro}

Participatory processes like public comment periods on draft policies are said to provide democratic legitimacy [@Croley2003; @Rosenbloom2003], political oversight opportunities [@Balla1998; @McCubbins1984],  and new technical information [@Yackee2006JPART; @Nelson2012]. The extent to which participatory processes serve these democratic, accountablity, or technocratic goals depends on who participates and why.

In civics classrooms and Norman Rockwell paintings, raising concerns to government is an individual affair. Scholars, too, often focus on studying and improving the ability of individuals to participate in policymaking [@Cuellar2005]. But in practice, the capacities required to lobby effectively on matters of national policy are those of organized groups, not individual citizens.

<!--PUZZLE-->
Bureaucratic policymaking, in particular, is the ideal context for powerful organized interests to dominate. Policies made by specialized agencies are likely to have concentrated benefits or costs that lead interest groups, especially businesses, to dominate [@Lowi1969; @Lowi1972]. Agency policymakers are generally experts who are deeply embeded in the professional and epistemic networks of the industries they support and regulate. Organizations with superior resources often flood policymakers with technical information that is valued both by the specic legal context of bureaucratic policymaking and by technocratic rationality more broadly [@Wagner2010]. Agencies are generally framed as "implimenters" rather than "makers" of policy. Even the most value-laden policy documents that are re-written under each subsiquent president are framed as deriviative of (often decades-old) legislative statutes. All of these things empower legal and technical experts and thus the organizations with the resources to hire them.

<!--PUZZEL-->
And yet, activists frequently target agency policymaking with letter-writing campaigns, petitions, protests,
and mobilizing people to attend hearings---all classic examples of "civic engagement" [@Verba1987]. While recent scholarship on agency policymaking has shed light on sophisticated lobbying, especially by businesses, we know surprisingly little about the vast majority of public comments, which are submitted by ordinary people as part of public pressure campaigns. As I show below, most comments submitted to regulations.gov are part of organized campaigns, more akin to petition signatures than "deliberative" participation or sophisticated lobbying.

<!--GAP-->
While practitioners and administrative law scholars have long pondered
what to make of letter-writing campaigns targeting the bureaucracy, political scientists have had
surprisingly little to say about this kind of civic participation and the role of public pressure in bureaucratic policymaking. Much of our knowledge about civic participation beyond voting comes from surveys [e.g., @Verba1987] and qualitative studies of particular groups. 
Models of bureaucratic policymaking focus on the participation of sophisticated lobbying groups and neither explain nor account for public pressure campaigns.
Civic engagement in general and organized public pressure in particular thus remain poorly understood in the context of bureaucratic policymaking. 

To fill this gap, I bring scholarship on policy advocacy groups^[Organizations that mobilize people to engage in policy debates (e.g., through letter-writing campaigns) go by many names, each with slightly different connotations. These include pressure groups, policy advocacy groups [@Potter2017], citizen groups [@Berry1999], policy change organizations [@McNutt2005]. TODO: NAIL DOWN MY NOMENCLATURE.] into theories of bureaucratic policymaking. Doing so reveals competing intuitions about the drivers of public participation, which I assess using a large new dataset of participation in federal agency rulemaking. 

First, I develop and assess two theories of who should mobilize public pressure campaigns and why.  Each theory has observable implications for which types of groups will run campaigns in different contexts. One stems from leading theories of bureaucratic decision-making and interest group lobbying. It predicts that groups with more resources will dominate all forms of lobbying, including public pressure campaigns. The other emerges from democratic theories. It predicts that groups with fewer material resources but more popular support will more often use public pressure campaigns. <!--Schattschneider1975 Kollman1998-->
The extent to which public comment periods serve the functions and provide the normative benefits that proponents assert depends on who participates. To begin to make sense of public participation in bureaucratic policymaking, I develop a typology of different kinds of participation, with implications for the normative value of participatory institutions. Because political participation is often a collective affair, this includes a typology of public pressure campaigns. 

To the extent that public pressure campaigns drive participation, the normative value of participatory processes like public comment periods depends on who organizes these campaigns. 
 Suppose public pressure campaigns follow the usual patterns of interest group lobbying, where the groups with the most resources dominate. In that case, the procedural legitimacy they provide is merely a veneer masking the influence of powerful political insiders. Instead of encouraging political oversight, they would discourage it. Instead of diversifying the available information, they would merely reinforce the claims and issue frames of powerful insiders. We would expect a pressure campaign to push policy further in the direction desired by the most powerful insiders.
On the other hand, if the usual suspects do not dominate public pressure campaigns, they may yet improve the democratic credentials of American policymaking, expand political oversight, and diversify the information available to policymakers. To the extent that public pressure tactics empower groups who are usually left out of the policy process, pressure campaigns may blunt the influence of powerful insiders.
Thus, to understand the empirical effects or normative value of participatory processes like public comment periods, we first need to know who participates and why. To the extent that public participation is mobilzed by campaigns, we need to know who is behind them.

Second, I offer a synthetic theory about the conditions under which we should see private and public interest group campaigns. I argue that public interest groups more often have incentives to launch public pressure campaigns than private interests. However, the resources required to run a campaign will lead a few large public interest groups to dominate. I argue that private interests have incentives to sponsor campaigns (including astroturf campaigns) under much more limited conditions and should thus be less common.^[However, astroturf campaigns are most likely to occur precisely when public pressure is most decisive, so they may still present a normative concern.]

To assess these theories, I assemble a new dataset of thousands of public pressure campaigns that collectively mobilized millions of public comments across three administrations from 2005 to 2020. Using a mix of qualitative hand-coding and computational text analysis, I identify the coalitions of groups behind each campaign and the type of interest group they represent. 

I find that mass participation in bureaucratic policymaking is better explained by theories of democratic institutions and conflict expansion rather than existing theories of bureaucratic policymaking. Participation is overwhelmingly driven by the policy advocacy efforts of a few public interest groups. Indeed, just 100 advocacy organizations mobilized over 80% of public comments (40 out of 50 million). Traditional membership organizations and individuals account for a smaller portion, and "astroturf" campaigns are rare, almost exclusivly arising in opposition to a large public interst group campaign, as predicted by my theory.

<!--broaden public participation, political oversight, and relevant information--and their ultimate impact on policy depends on who organizes them. If 
<!--Observers often ask how effective public pressure campaigns are. From a political science perspective, the question is 
Increasing civic engagement, oversight, and information,-->

